-- Seed canonical reason codes into eod_reason_codes.
-- Safe to rerun: uses ON DUPLICATE KEY UPDATE for description/severity/category/is_active.

INSERT INTO eod_reason_codes (`code`, `category`, `description`, `severity`, `is_active`) VALUES
('RUN_COVERAGE_LOW', 'RUN', 'Coverage ratio for the requested date is below the locked minimum threshold.', 'HARD', 1),
('RUN_COVERAGE_NOT_EVALUABLE', 'RUN', 'Coverage could not be evaluated meaningfully for the requested date, so requested-date publication must remain not readable.', 'HARD', 1),
('COVERAGE_THRESHOLD_MET', 'COVERAGE', 'Coverage evaluation passed because available canonical EOD bars met or exceeded the locked minimum threshold.', 'INFO', 1),
('COVERAGE_BELOW_THRESHOLD', 'COVERAGE', 'Coverage evaluation failed because available canonical EOD bars stayed below the locked minimum threshold.', 'HARD', 1),
('COVERAGE_UNIVERSE_EMPTY', 'COVERAGE', 'Coverage could not be evaluated because the resolved coverage universe for the requested date was empty.', 'HARD', 1),
('RUN_INDICATORS_MISSING', 'RUN', 'Required indicator artifact or required indicator row set for the requested date is not available.', 'HARD', 1),
('RUN_ELIGIBILITY_MISSING', 'RUN', 'Eligibility snapshot for the requested date is not available.', 'HARD', 1),
('RUN_HASH_MISSING', 'RUN', 'One or more mandatory content hashes are missing at finalization time.', 'HARD', 1),
('RUN_HASH_FAILED', 'RUN', 'Hash computation failed or produced unusable output.', 'HARD', 1),
('RUN_SEAL_PRECONDITION_FAILED', 'RUN', 'Seal execution was attempted before all locked preconditions were satisfied.', 'HARD', 1),
('RUN_SEAL_WRITE_FAILED', 'RUN', 'Seal metadata could not be written successfully.', 'HARD', 1),
('DATASET_HASH_CREATED', 'DATASET', 'Dataset hash was created from canonical serialized artifact rows.', 'INFO', 1),
('DATASET_HASH_VERIFIED', 'DATASET', 'Dataset hash/seal context was verified against stored canonical manifest context.', 'INFO', 1),
('DATASET_HASH_MISSING', 'DATASET', 'Dataset seal or finalize was blocked because mandatory artifact hash context is missing.', 'HARD', 1),
('DATASET_HASH_MISMATCH', 'DATASET', 'Recomputed or mirrored dataset hash does not match stored artifact hash context.', 'HARD', 1),
('DATASET_MANIFEST_INVALID', 'DATASET', 'Dataset manifest is missing required run/date/source/hash/coverage context.', 'HARD', 1),
('DATASET_SEAL_INVALID', 'DATASET', 'Dataset seal state is invalid or cannot be verified from manifest/hash context.', 'HARD', 1),
('SEALED_DATASET_MUTATION_BLOCKED', 'DATASET', 'Runtime attempted to mutate a sealed/finalized/readable dataset through a normal artifact path and was blocked.', 'HARD', 1),
('FINALIZE_HASH_MISSING', 'RUN', 'Finalize was blocked because the candidate publication or run is missing mandatory hash context.', 'HARD', 1),
('FINALIZE_HASH_MISMATCH', 'RUN', 'Finalize was blocked because run hash context differs from candidate publication hash context.', 'HARD', 1),
('FINALIZE_SEAL_MISSING', 'RUN', 'Finalize was blocked because candidate publication seal state is missing.', 'HARD', 1),
('FINALIZE_SEAL_INVALID', 'RUN', 'Finalize was blocked because candidate publication seal timestamp or verification context is invalid.', 'HARD', 1),
('RUN_FINALIZE_BEFORE_CUTOFF', 'RUN', 'Final success was attempted before the cutoff policy allowed it.', 'HARD', 1),
('RUN_LOCK_CONFLICT', 'RUN', 'Run-ownership conflict or duplicate writer activity occurred during hash, seal, or finalize stages.', 'HARD', 1),
('RUN_FINALIZE_IDEMPOTENCY_POINTER_INVALID', 'RUN', 'A previously completed readable finalize run no longer matches the current publication pointer and must be fail-safed before idempotent short-circuit.', 'HARD', 1),
('RUN_SOURCE_TIMEOUT', 'RUN', 'The source timed out and retry policy was already applied or exhausted.', 'WARN', 1),
('RUN_SOURCE_RATE_LIMIT', 'RUN', 'The source hit rate limiting and affected data acquisition.', 'WARN', 1),
('RUN_SOURCE_AUTH_ERROR', 'RUN', 'Source authentication failure or credential/config error blocked data acquisition.', 'HARD', 1),
('RUN_SOURCE_RESPONSE_CHANGED', 'RUN', 'A source schema or response-contract change was detected.', 'HARD', 1),
('RUN_SOURCE_PARTIAL_COVERAGE', 'RUN', 'The source returned incomplete symbol coverage for the requested date.', 'WARN', 1),
('RUN_SOURCE_PARTIAL_RESPONSE', 'RUN', 'The source adapter returned only part of the requested provider response and coverage gate must decide publishability.', 'WARN', 1),
('RUN_SOURCE_MANUAL_FILE_NOT_FOUND', 'RUN', 'The configured manual-file source was not found.', 'HARD', 1),
('RUN_SOURCE_MANUAL_FILE_NOT_READABLE', 'RUN', 'The configured manual-file source could not be opened or read.', 'HARD', 1),
('RUN_SOURCE_MANUAL_FILE_MALFORMED', 'RUN', 'The configured manual-file source could not be parsed or normalized safely.', 'HARD', 1),
('RUN_SOURCE_MODE_UNSUPPORTED', 'RUN', 'The requested source mode is not supported by the selected source adapter.', 'HARD', 1),
('RUN_PARTIAL_DATA', 'RUN', 'Coverage failed because only part of the requested-date universe had canonical valid EOD data.', 'HARD', 1),
('RUN_DATA_DELAYED', 'RUN', 'Coverage failed while requested-date data was still inside the controlled delayed-data window.', 'WARN', 1),
('RUN_STALE_DATA', 'RUN', 'Source rows were outside the requested trade date and must not count as available coverage.', 'HARD', 1),
('RUN_SOURCE_MALFORMED_PAYLOAD', 'RUN', 'The source payload could not be normalized safely.', 'HARD', 1),
('BAR_DUPLICATE_SOURCE_ROW', 'BAR', 'More than one source row mapped to the same (trade_date, ticker_id), requiring deterministic winner selection.', 'WARN', 1),
('BAR_INVALID_OHLC_ORDER', 'BAR', 'Received OHLC values violated canonical ordering rules.', 'HARD', 1),
('BAR_NON_POSITIVE_PRICE', 'BAR', 'Received price value was zero or negative in a field that must be positive.', 'HARD', 1),
('BAR_NEGATIVE_VOLUME', 'BAR', 'Received volume value was negative.', 'HARD', 1),
('BAR_MISSING_REQUIRED_FIELD', 'BAR', 'One or more mandatory source fields were missing.', 'HARD', 1),
('BAR_TICKER_MAPPING_MISSING', 'BAR', 'Source row ticker_code could not be resolved deterministically to ticker_id via the ticker master.', 'WARN', 1),
('IND_INSUFFICIENT_HISTORY', 'INDICATOR', 'Required trading-day history is not yet sufficient for deterministic indicator computation.', 'WARN', 1),
('IND_MISSING_DEPENDENCY_BAR', 'INDICATOR', 'A required canonical bar in the trading-day dependency chain is missing.', 'HARD', 1),
('IND_INVALID_BAR_INPUT', 'INDICATOR', 'A canonical bar input required for indicator computation is invalid.', 'HARD', 1),
('IND_COMPUTE_ERROR', 'INDICATOR', 'Indicator computation failed because of logic or runtime error.', 'HARD', 1),
('ELIG_MISSING_BAR', 'ELIGIBILITY', 'A ticker in the coverage universe does not have a canonical valid bar for the requested date.', 'WARN', 1),
('ELIG_MISSING_INDICATORS', 'ELIGIBILITY', 'Eligibility cannot be determined because required indicators are unavailable.', 'HARD', 1),
('ELIG_INVALID_INDICATORS', 'ELIGIBILITY', 'An indicator row exists but required indicators are marked invalid.', 'WARN', 1),
('ELIG_INSUFFICIENT_HISTORY', 'ELIGIBILITY', 'Eligibility is blocked because required indicator history is still insufficient.', 'WARN', 1),
('ELIG_UNIVERSE_DEPENDENCY_MISSING', 'ELIGIBILITY', 'An upstream dependency required to determine universe membership is unavailable.', 'HARD', 1),
('ELIG_FETCH_FAILURE', 'ELIGIBILITY', 'Eligibility is blocked because ticker-level source acquisition failed and required upstream artifacts could not be formed safely.', 'WARN', 1),
('SNAP_SOURCE_TIMEOUT', 'INTRADAY', 'The session-snapshot source timed out.', 'WARN', 1),
('SNAP_SOURCE_RATE_LIMIT', 'INTRADAY', 'The session-snapshot source hit rate limiting.', 'WARN', 1),
('SNAP_PARTIAL_SCOPE', 'INTRADAY', 'The session snapshot captured only part of the planned scope.', 'WARN', 1),
('SNAP_SOURCE_ERROR', 'INTRADAY', 'The session-snapshot source failed for an operational reason that does not block EOD.', 'WARN', 1),
('COMMAND_MISSING_REQUIRED_INPUT', 'COMMAND', 'Operator command input is missing or empty for a required argument or option.', 'HARD', 1),
('COMMAND_INVALID_DATE_FORMAT', 'COMMAND', 'Operator command date input does not use the locked YYYY-MM-DD format.', 'HARD', 1),
('COMMAND_INVALID_SOURCE_MODE', 'COMMAND', 'Operator command source mode is outside the locked API/manual-file source modes.', 'HARD', 1),
('COMMAND_INVALID_PROMOTE_MODE', 'COMMAND', 'Operator command promote mode is unsupported by the locked promote contract.', 'HARD', 1),
('COMMAND_CONFLICTING_OPTIONS', 'COMMAND', 'Operator command options are mutually exclusive or ambiguous.', 'HARD', 1),
('COMMAND_DESTRUCTIVE_GUARD_REQUIRED', 'COMMAND', 'Operator command requested a destructive or force action without the required explicit guard/reason.', 'HARD', 1),
('COMMAND_DRY_RUN_ONLY', 'COMMAND', 'Operator command completed a dry-run preview and intentionally did not mutate final state.', 'INFO', 1),
('COMMAND_APPLY_CONFIRMED', 'COMMAND', 'Operator command mutation was executed only after explicit apply confirmation.', 'INFO', 1),
('COMMAND_EXECUTION_FAILED', 'COMMAND', 'Operator command execution failed and surfaced a reason-coded blocking outcome.', 'HARD', 1),
('COMMAND_CORRECTION_NOT_FOUND', 'COMMAND', 'Operator command referenced a correction id that does not exist.', 'HARD', 1),
('COMMAND_CORRECTION_STATUS_NOT_EXECUTABLE', 'COMMAND', 'Operator command attempted to execute a correction whose lifecycle status is not executable.', 'HARD', 1),
('RUN_COMPUTE_FAILED', 'RUN', 'Indicator computation stage failed and the run cannot continue silently.', 'HARD', 1),
('RUN_COVERAGE_EVALUATION_FAILED', 'RUN', 'Coverage evaluation failed before a deterministic gate result could be persisted.', 'HARD', 1),
('RUN_ELIGIBILITY_FAILED', 'RUN', 'Eligibility build stage failed and the run cannot continue silently.', 'HARD', 1),
('RUN_FINALIZE_FAILED', 'RUN', 'Finalize stage failed before a safe terminal state could be completed.', 'HARD', 1),
('RUN_NON_CURRENT_PROMOTION', 'RUN', 'Promotion was requested for a target that must not become the current readable publication.', 'HARD', 1),
('RUN_REPAIR_CANDIDATE_PARTIAL', 'RUN', 'Repair candidate is intentionally partial and must not be promoted as normal current readable data.', 'WARN', 1),
('RUN_CURRENT_PUBLICATION_INTEGRITY_REPAIRED', 'RUN', 'Current publication mirror or pointer integrity was repaired or fail-safed to preserve readable-state contract.', 'WARN', 1),
('RUN_TERMINAL_STATUS_NOT_SUCCESS', 'RUN', 'Publication pointer validation found a run whose terminal status is not SUCCESS.', 'HARD', 1),
('RUN_PUBLISHABILITY_NOT_READABLE', 'RUN', 'Publication pointer validation found a run whose publishability state is not READABLE.', 'HARD', 1),
('RUN_COVERAGE_GATE_NOT_PASS', 'RUN', 'Publication pointer validation found a run whose coverage gate state is not PASS.', 'HARD', 1),
('RUN_COVERAGE_TELEMETRY_INVALID', 'RUN', 'Readable pointer validation found invalid coverage telemetry for a candidate run.', 'HARD', 1),
('RUN_CURRENT_MIRROR_NOT_SET', 'RUN', 'Readable pointer validation found that the run current-publication mirror is not set.', 'HARD', 1),
('RUN_PUBLICATION_ID_MISMATCH', 'RUN', 'Readable pointer validation found a mismatch between run publication id and pointer publication id.', 'HARD', 1),
('RUN_PUBLICATION_VERSION_MISMATCH', 'RUN', 'Readable pointer validation found a mismatch between run publication version and pointer publication version.', 'HARD', 1),
('RUN_ROW_MISSING', 'RUN', 'Readable pointer validation could not find the linked run row.', 'HARD', 1),
('RUN_SEALED_AT_MISSING', 'RUN', 'Readable pointer validation found the linked run has no sealed timestamp.', 'HARD', 1),
('PUBLICATION_ROW_MISSING', 'PUBLICATION', 'Current pointer validation could not find the linked publication row.', 'HARD', 1),
('PUBLICATION_TRADE_DATE_MISMATCH', 'PUBLICATION', 'Current pointer validation found publication trade date mismatch.', 'HARD', 1),
('PUBLICATION_NOT_MARKED_CURRENT', 'PUBLICATION', 'Current pointer validation found the publication row is not marked current.', 'HARD', 1),
('PUBLICATION_NOT_SEALED', 'PUBLICATION', 'Current pointer validation found the publication is not SEALED.', 'HARD', 1),
('PUBLICATION_SEALED_AT_MISSING', 'PUBLICATION', 'Current pointer validation found a sealed publication without sealed timestamp.', 'HARD', 1),
('POINTER_RUN_ID_MISMATCH', 'POINTER', 'Current pointer validation found run id mismatch between pointer and publication/run context.', 'HARD', 1),
('POINTER_PUBLICATION_ID_MISMATCH', 'POINTER', 'Current pointer validation found publication id mismatch between expected and resolved pointer target.', 'HARD', 1),
('POINTER_PUBLICATION_VERSION_MISMATCH', 'POINTER', 'Current pointer validation found publication version mismatch.', 'HARD', 1),
('POINTER_SEALED_AT_MISSING', 'POINTER', 'Current pointer validation found pointer sealed timestamp is missing.', 'HARD', 1),
('RUN_PUBLICATION_LINK_CREATED', 'RUN', 'Publication lineage link was created from a valid originating run.', 'INFO', 1),
('RUN_PUBLICATION_LINK_VERIFIED', 'RUN', 'Publication lineage link to its originating run was verified.', 'INFO', 1),
('RUN_PUBLICATION_LINK_MISSING', 'RUN', 'Publication lineage is missing either the publication row or originating run.', 'HARD', 1),
('RUN_PUBLICATION_LINK_INVALID', 'RUN', 'Publication lineage points to an invalid originating run or invalid publication context.', 'HARD', 1),
('RUN_PUBLICATION_MIRROR_MISMATCH', 'RUN', 'Run-publication mirror fields disagree across run, publication, pointer, or trade-date context.', 'HARD', 1),
('PUBLICATION_RUN_NOT_FOUND', 'PUBLICATION', 'Publication lineage points to a run id that cannot be found.', 'HARD', 1),
('PUBLICATION_RUN_STATE_INVALID', 'PUBLICATION', 'Publication lineage points to a run whose state cannot produce a readable/current publication.', 'HARD', 1),
('POINTER_PUBLICATION_LINK_CREATED', 'POINTER', 'Current pointer linkage to a publication was created.', 'INFO', 1),
('POINTER_PUBLICATION_LINK_VERIFIED', 'POINTER', 'Current pointer linkage to its target publication was verified.', 'INFO', 1),
('POINTER_PUBLICATION_LINK_MISSING', 'POINTER', 'Current pointer linkage is missing the target publication relationship.', 'HARD', 1),
('POINTER_PUBLICATION_LINK_INVALID', 'POINTER', 'Current pointer linkage points to an invalid publication target.', 'HARD', 1),
('POINTER_PUBLICATION_NOT_FOUND', 'POINTER', 'Current pointer target publication row could not be found.', 'HARD', 1),
('POINTER_PUBLICATION_TRADE_DATE_MISMATCH', 'POINTER', 'Current pointer target publication trade date does not match pointer trade date.', 'HARD', 1),
('POINTER_PUBLICATION_STATE_INVALID', 'POINTER', 'Current pointer target publication or run state is not readable/current-safe.', 'HARD', 1),
('POINTER_PUBLICATION_SEAL_INVALID', 'POINTER', 'Current pointer target publication is not sealed with valid seal metadata.', 'HARD', 1),
('POINTER_PUBLICATION_HASH_INVALID', 'POINTER', 'Current pointer target publication hash context is missing or mismatched.', 'HARD', 1),
('POINTER_ORPHAN_DETECTED', 'POINTER', 'Current pointer is orphaned from a valid publication/run lineage.', 'HARD', 1),
('POINTER_SWITCH_STARTED', 'POINTER', 'Atomic pointer switch validation started.', 'INFO', 1),
('POINTER_SWITCH_COMPLETED', 'POINTER', 'Atomic pointer switch completed after validation.', 'INFO', 1),
('POINTER_SWITCH_FAILED', 'POINTER', 'Atomic pointer switch failed before a valid current publication was established.', 'HARD', 1),
('POINTER_SWITCH_ROLLED_BACK', 'POINTER', 'Pointer switch was rolled back or previous current publication was restored.', 'WARN', 1),
('POINTER_POST_SWITCH_VERIFIED', 'POINTER', 'Pointer resolver returned the promoted publication after switch.', 'INFO', 1),
('POINTER_POST_SWITCH_MISMATCH', 'POINTER', 'Pointer resolver did not return the expected promoted publication after switch.', 'HARD', 1),
('CURRENT_PUBLICATION_DEMOTED', 'PUBLICATION', 'Previous current publication was demoted during an allowed pointer switch.', 'INFO', 1),
('CURRENT_PUBLICATION_PROMOTED', 'PUBLICATION', 'Candidate publication was promoted to current after all validation passed.', 'INFO', 1),
('CURRENT_PUBLICATION_REPLACE_BLOCKED', 'PUBLICATION', 'Replacement of an existing current publication was blocked because force/audit controls were missing or invalid.', 'HARD', 1),
('CURRENT_PUBLICATION_FORCE_REPLACED', 'PUBLICATION', 'Operator-controlled force replace switched current publication with audit reason.', 'WARN', 1),
('CORRECTION_BASELINE_LINK_VERIFIED', 'CORRECTION', 'Correction baseline publication/run linkage was verified.', 'INFO', 1),
('CORRECTION_BASELINE_LINK_MISSING', 'CORRECTION', 'Correction baseline publication/run linkage is missing.', 'HARD', 1),
('CORRECTION_BASELINE_LINK_INVALID', 'CORRECTION', 'Correction baseline linkage is not a valid current readable publication.', 'HARD', 1),
('CORRECTION_REPLACEMENT_LINK_CREATED', 'CORRECTION', 'Correction replacement publication/run linkage was created.', 'INFO', 1),
('CORRECTION_REPLACEMENT_LINK_VERIFIED', 'CORRECTION', 'Correction replacement publication/run linkage was verified before publication.', 'INFO', 1),
('CORRECTION_REPLACEMENT_LINK_INVALID', 'CORRECTION', 'Correction replacement publication/run linkage is invalid.', 'HARD', 1),
('CORRECTION_POINTER_SWITCH_CREATED', 'CORRECTION', 'Correction pointer switch was created for a valid replacement publication.', 'INFO', 1),
('CORRECTION_POINTER_SWITCH_BLOCKED', 'CORRECTION', 'Correction pointer switch was blocked because replacement or baseline linkage was unsafe.', 'HARD', 1),
('CORRECTION_LINEAGE_INCOMPLETE', 'CORRECTION', 'Correction lineage is incomplete across baseline, replacement, run, publication, or pointer switch.', 'HARD', 1),
('CORRECTION_BASELINE_POINTER_PRESERVED', 'CORRECTION', 'Correction preserved the baseline current pointer on unchanged or failed replacement.', 'INFO', 1),
('REPLAY_LINEAGE_MATCHED', 'REPLAY', 'Replay lineage matched expected run-publication-pointer-correction proof.', 'INFO', 1),
('REPLAY_RUN_PUBLICATION_MISMATCH', 'REPLAY', 'Replay detected a run-publication lineage mismatch.', 'HARD', 1),
('REPLAY_POINTER_PUBLICATION_MISMATCH', 'REPLAY', 'Replay detected a pointer-publication lineage mismatch.', 'HARD', 1),
('REPLAY_CORRECTION_LINEAGE_MISMATCH', 'REPLAY', 'Replay detected correction baseline/replacement lineage mismatch.', 'HARD', 1),
('EVIDENCE_LINEAGE_CONTEXT_INCLUDED', 'EVIDENCE', 'Evidence export included full run-publication-pointer-correction lineage context.', 'INFO', 1),
('EVIDENCE_RUN_PUBLICATION_CONTEXT_INCLUDED', 'EVIDENCE', 'Evidence export included run-publication linkage context.', 'INFO', 1),
('EVIDENCE_POINTER_CONTEXT_INCLUDED', 'EVIDENCE', 'Evidence export included current pointer target context.', 'INFO', 1),
('EVIDENCE_CORRECTION_LINEAGE_CONTEXT_INCLUDED', 'EVIDENCE', 'Evidence export included correction baseline/replacement lineage context.', 'INFO', 1),
('EVIDENCE_LINEAGE_CONTEXT_MISSING', 'EVIDENCE', 'Evidence export found missing lineage context and marked evidence incomplete.', 'WARN', 1),
('CORRECTION_ARTIFACT_BASELINE_OR_CANDIDATE_MISSING', 'CORRECTION', 'Correction artifact comparison cannot run because baseline or candidate publication is missing.', 'HARD', 1),
('CORRECTION_ARTIFACT_HASH_INCOMPLETE', 'CORRECTION', 'Correction artifact comparison found missing hash context and cannot prove deterministic change.', 'HARD', 1),
('CORRECTION_ARTIFACT_UNCHANGED', 'CORRECTION', 'Correction artifact comparison found no content change; current publication must be preserved.', 'INFO', 1),
('CORRECTION_ARTIFACT_CHANGED', 'CORRECTION', 'Correction artifact comparison found deterministic content change and reseal/publish may proceed through normal guards.', 'INFO', 1),
('CORRECTION_PUBLISHED', 'CORRECTION', 'Correction lifecycle published a changed, resealed publication safely.', 'INFO', 1),
('CORRECTION_FAILED', 'CORRECTION', 'Correction lifecycle failed or was blocked before safe publication.', 'HARD', 1),
('CORRECTION_CANCELLED', 'CORRECTION', 'Correction lifecycle was consumed without publication because current content was unchanged or cancelled safely.', 'INFO', 1),
('EVIDENCE_COMPLETE', 'EVIDENCE', 'Evidence export includes all required operator-grade context sections.', 'INFO', 1),
('EVIDENCE_INCOMPLETE', 'EVIDENCE', 'Evidence export completed with one or more missing context sections that must be visible to the operator.', 'WARN', 1),
('REPLAY_MATCH', 'REPLAY', 'Replay expected proof matched observed proof across deterministic fields.', 'INFO', 1),
('REPLAY_FIXTURE_SCHEMA_MISMATCH', 'REPLAY', 'Replay fixture manifest or schema version does not match the locked replay fixture contract.', 'HARD', 1),
('REPLAY_EXPECTED_PROOF_INCOMPLETE', 'REPLAY', 'Replay expected proof package is missing required deterministic lifecycle context.', 'HARD', 1),
('REPLAY_ACTUAL_PROOF_INCOMPLETE', 'REPLAY', 'Replay actual proof package is missing required lifecycle evidence.', 'HARD', 1),
('REPLAY_REQUESTED_DATE_MISMATCH', 'REPLAY', 'Replay requested trade date differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_EFFECTIVE_DATE_MISMATCH', 'REPLAY', 'Replay effective trade date differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_REQUEST_MODE_MISMATCH', 'REPLAY', 'Replay request/promote/publish target context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SOURCE_MODE_MISMATCH', 'REPLAY', 'Replay source mode differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SOURCE_IDENTITY_MISMATCH', 'REPLAY', 'Replay source identity or source row-count context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SOURCE_FILE_HASH_MISMATCH', 'REPLAY', 'Replay manual source file hash differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_PROVIDER_CONTEXT_MISMATCH', 'REPLAY', 'Replay provider/API retry, timeout, or HTTP context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_COVERAGE_STATE_MISMATCH', 'REPLAY', 'Replay coverage gate state or coverage count context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_COVERAGE_RATIO_MISMATCH', 'REPLAY', 'Replay coverage ratio or threshold differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_COVERAGE_REASON_MISMATCH', 'REPLAY', 'Replay coverage reason code differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_ARTIFACT_HASH_MISMATCH', 'REPLAY', 'Replay artifact hash or artifact row-count context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SEAL_STATE_MISMATCH', 'REPLAY', 'Replay seal state differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_PUBLICATION_STATE_MISMATCH', 'REPLAY', 'Replay publication state/readability context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_PUBLICATION_VERSION_MISMATCH', 'REPLAY', 'Replay publication version differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_POINTER_TARGET_MISMATCH', 'REPLAY', 'Replay pointer target differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_POINTER_RESOLUTION_MISMATCH', 'REPLAY', 'Replay pointer resolution state differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_FALLBACK_CONTEXT_MISMATCH', 'REPLAY', 'Replay fallback context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_CORRECTION_BASELINE_MISMATCH', 'REPLAY', 'Replay correction baseline or candidate publication context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_FINAL_STATUS_MISMATCH', 'REPLAY', 'Replay final terminal or publishability state differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_FINAL_REASON_CODE_MISMATCH', 'REPLAY', 'Replay final reason code or reason-code counts differ between expected proof and actual proof.', 'HARD', 1),
('REPLAY_LINEAGE_MISMATCH', 'REPLAY', 'Replay lineage chain differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_UNEXPECTED_SUCCESS', 'REPLAY', 'Replay produced a success-looking result when the expected proof required failure or degrade.', 'HARD', 1),
('REPLAY_UNEXPECTED_FAILURE', 'REPLAY', 'Replay produced failure when the expected proof required a successful deterministic match.', 'HARD', 1),
('REPLAY_NON_DETERMINISTIC_OUTPUT', 'REPLAY', 'Replay output contains a deterministic-field mismatch not covered by a more specific replay reason code.', 'HARD', 1)
ON DUPLICATE KEY UPDATE
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `severity` = VALUES(`severity`),
  `is_active` = VALUES(`is_active`);