-- Seed canonical reason codes into eod_reason_codes.
-- Safe to rerun: uses ON DUPLICATE KEY UPDATE for description/severity/category/is_active.

INSERT INTO eod_reason_codes (`code`, `category`, `description`, `severity`, `is_active`) VALUES
('RUN_COVERAGE_LOW', 'RUN', 'Coverage ratio for the requested date is below the locked minimum threshold.', 'HARD', 1),
('RUN_COVERAGE_NOT_EVALUABLE', 'RUN', 'Coverage could not be evaluated meaningfully for the requested date, so requested-date publication must remain not readable.', 'HARD', 1),
('COVERAGE_THRESHOLD_MET', 'COVERAGE', 'Coverage evaluation passed because available canonical EOD bars met or exceeded the locked minimum threshold.', 'INFO', 1),
('COVERAGE_BELOW_THRESHOLD', 'COVERAGE', 'Coverage evaluation failed because available canonical EOD bars stayed below the locked minimum threshold.', 'HARD', 1),
('COVERAGE_UNIVERSE_EMPTY', 'COVERAGE', 'Coverage could not be evaluated because the resolved coverage universe for the requested date was empty.', 'HARD', 1),
('RUN_INDICATORS_MISSING', 'RUN', 'Required indicator artifact or required indicator row set for the requested date is not available.', 'HARD', 1),
('RUN_ELIGIBILITY_MISSING', 'RUN', 'Eligibility snapshot for the requested date is not available.', 'HARD', 1),
('RUN_HASH_MISSING', 'RUN', 'One or more mandatory content hashes are missing at finalization time.', 'HARD', 1),
('RUN_HASH_FAILED', 'RUN', 'Hash computation failed or produced unusable output.', 'HARD', 1),
('RUN_SEAL_PRECONDITION_FAILED', 'RUN', 'Seal execution was attempted before all locked preconditions were satisfied.', 'HARD', 1),
('RUN_SEAL_WRITE_FAILED', 'RUN', 'Seal metadata could not be written successfully.', 'HARD', 1),
('RUN_FINALIZE_BEFORE_CUTOFF', 'RUN', 'Final success was attempted before the cutoff policy allowed it.', 'HARD', 1),
('RUN_LOCK_CONFLICT', 'RUN', 'Run-ownership conflict or duplicate writer activity occurred during hash, seal, or finalize stages.', 'HARD', 1),
('RUN_FINALIZE_IDEMPOTENCY_POINTER_INVALID', 'RUN', 'A previously completed readable finalize run no longer matches the current publication pointer and must be fail-safed before idempotent short-circuit.', 'HARD', 1),
('RUN_SOURCE_TIMEOUT', 'RUN', 'The source timed out and retry policy was already applied or exhausted.', 'WARN', 1),
('RUN_SOURCE_RATE_LIMIT', 'RUN', 'The source hit rate limiting and affected data acquisition.', 'WARN', 1),
('RUN_SOURCE_AUTH_ERROR', 'RUN', 'Source authentication failure or credential/config error blocked data acquisition.', 'HARD', 1),
('RUN_SOURCE_RESPONSE_CHANGED', 'RUN', 'A source schema or response-contract change was detected.', 'HARD', 1),
('RUN_SOURCE_PARTIAL_COVERAGE', 'RUN', 'The source returned incomplete symbol coverage for the requested date.', 'WARN', 1),
('RUN_SOURCE_PARTIAL_RESPONSE', 'RUN', 'The source adapter returned only part of the requested provider response and coverage gate must decide publishability.', 'WARN', 1),
('RUN_SOURCE_MANUAL_FILE_NOT_FOUND', 'RUN', 'The configured manual-file source was not found.', 'HARD', 1),
('RUN_SOURCE_MANUAL_FILE_NOT_READABLE', 'RUN', 'The configured manual-file source could not be opened or read.', 'HARD', 1),
('RUN_SOURCE_MANUAL_FILE_MALFORMED', 'RUN', 'The configured manual-file source could not be parsed or normalized safely.', 'HARD', 1),
('RUN_SOURCE_MODE_UNSUPPORTED', 'RUN', 'The requested source mode is not supported by the selected source adapter.', 'HARD', 1),
('RUN_PARTIAL_DATA', 'RUN', 'Coverage failed because only part of the requested-date universe had canonical valid EOD data.', 'HARD', 1),
('RUN_DATA_DELAYED', 'RUN', 'Coverage failed while requested-date data was still inside the controlled delayed-data window.', 'WARN', 1),
('RUN_STALE_DATA', 'RUN', 'Source rows were outside the requested trade date and must not count as available coverage.', 'HARD', 1),
('RUN_SOURCE_MALFORMED_PAYLOAD', 'RUN', 'The source payload could not be normalized safely.', 'HARD', 1),
('BAR_DUPLICATE_SOURCE_ROW', 'BAR', 'More than one source row mapped to the same (trade_date, ticker_id), requiring deterministic winner selection.', 'WARN', 1),
('BAR_INVALID_OHLC_ORDER', 'BAR', 'Received OHLC values violated canonical ordering rules.', 'HARD', 1),
('BAR_NON_POSITIVE_PRICE', 'BAR', 'Received price value was zero or negative in a field that must be positive.', 'HARD', 1),
('BAR_NEGATIVE_VOLUME', 'BAR', 'Received volume value was negative.', 'HARD', 1),
('BAR_MISSING_REQUIRED_FIELD', 'BAR', 'One or more mandatory source fields were missing.', 'HARD', 1),
('BAR_TICKER_MAPPING_MISSING', 'BAR', 'Source row ticker_code could not be resolved deterministically to ticker_id via the ticker master.', 'WARN', 1),
('IND_INSUFFICIENT_HISTORY', 'INDICATOR', 'Required trading-day history is not yet sufficient for deterministic indicator computation.', 'WARN', 1),
('IND_MISSING_DEPENDENCY_BAR', 'INDICATOR', 'A required canonical bar in the trading-day dependency chain is missing.', 'HARD', 1),
('IND_INVALID_BAR_INPUT', 'INDICATOR', 'A canonical bar input required for indicator computation is invalid.', 'HARD', 1),
('IND_COMPUTE_ERROR', 'INDICATOR', 'Indicator computation failed because of logic or runtime error.', 'HARD', 1),
('ELIG_MISSING_BAR', 'ELIGIBILITY', 'A ticker in the coverage universe does not have a canonical valid bar for the requested date.', 'WARN', 1),
('ELIG_MISSING_INDICATORS', 'ELIGIBILITY', 'Eligibility cannot be determined because required indicators are unavailable.', 'HARD', 1),
('ELIG_INVALID_INDICATORS', 'ELIGIBILITY', 'An indicator row exists but required indicators are marked invalid.', 'WARN', 1),
('ELIG_INSUFFICIENT_HISTORY', 'ELIGIBILITY', 'Eligibility is blocked because required indicator history is still insufficient.', 'WARN', 1),
('ELIG_UNIVERSE_DEPENDENCY_MISSING', 'ELIGIBILITY', 'An upstream dependency required to determine universe membership is unavailable.', 'HARD', 1),
('ELIG_FETCH_FAILURE', 'ELIGIBILITY', 'Eligibility is blocked because ticker-level source acquisition failed and required upstream artifacts could not be formed safely.', 'WARN', 1),
('SNAP_SOURCE_TIMEOUT', 'INTRADAY', 'The session-snapshot source timed out.', 'WARN', 1),
('SNAP_SOURCE_RATE_LIMIT', 'INTRADAY', 'The session-snapshot source hit rate limiting.', 'WARN', 1),
('SNAP_PARTIAL_SCOPE', 'INTRADAY', 'The session snapshot captured only part of the planned scope.', 'WARN', 1),
('SNAP_SOURCE_ERROR', 'INTRADAY', 'The session-snapshot source failed for an operational reason that does not block EOD.', 'WARN', 1),
('COMMAND_MISSING_REQUIRED_INPUT', 'COMMAND', 'Operator command input is missing or empty for a required argument or option.', 'HARD', 1),
('COMMAND_INVALID_DATE_FORMAT', 'COMMAND', 'Operator command date input does not use the locked YYYY-MM-DD format.', 'HARD', 1),
('COMMAND_INVALID_SOURCE_MODE', 'COMMAND', 'Operator command source mode is outside the locked API/manual-file source modes.', 'HARD', 1),
('COMMAND_INVALID_PROMOTE_MODE', 'COMMAND', 'Operator command promote mode is unsupported by the locked promote contract.', 'HARD', 1),
('COMMAND_CONFLICTING_OPTIONS', 'COMMAND', 'Operator command options are mutually exclusive or ambiguous.', 'HARD', 1),
('COMMAND_DESTRUCTIVE_GUARD_REQUIRED', 'COMMAND', 'Operator command requested a destructive or force action without the required explicit guard/reason.', 'HARD', 1),
('COMMAND_DRY_RUN_ONLY', 'COMMAND', 'Operator command completed a dry-run preview and intentionally did not mutate final state.', 'INFO', 1),
('COMMAND_APPLY_CONFIRMED', 'COMMAND', 'Operator command mutation was executed only after explicit apply confirmation.', 'INFO', 1),
('COMMAND_EXECUTION_FAILED', 'COMMAND', 'Operator command execution failed and surfaced a reason-coded blocking outcome.', 'HARD', 1),
('COMMAND_CORRECTION_NOT_FOUND', 'COMMAND', 'Operator command referenced a correction id that does not exist.', 'HARD', 1),
('COMMAND_CORRECTION_STATUS_NOT_EXECUTABLE', 'COMMAND', 'Operator command attempted to execute a correction whose lifecycle status is not executable.', 'HARD', 1),
('REPLAY_FIXTURE_SCHEMA_MISMATCH', 'REPLAY', 'Replay fixture manifest or schema version does not match the locked replay fixture contract.', 'HARD', 1),
('REPLAY_EXPECTED_PROOF_INCOMPLETE', 'REPLAY', 'Replay expected proof package is missing required deterministic lifecycle context.', 'HARD', 1),
('REPLAY_ACTUAL_PROOF_INCOMPLETE', 'REPLAY', 'Replay actual proof package is missing required lifecycle evidence.', 'HARD', 1),
('REPLAY_REQUESTED_DATE_MISMATCH', 'REPLAY', 'Replay requested trade date differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_EFFECTIVE_DATE_MISMATCH', 'REPLAY', 'Replay effective trade date differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_REQUEST_MODE_MISMATCH', 'REPLAY', 'Replay request/promote/publish target context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SOURCE_MODE_MISMATCH', 'REPLAY', 'Replay source mode differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SOURCE_IDENTITY_MISMATCH', 'REPLAY', 'Replay source identity or source row-count context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SOURCE_FILE_HASH_MISMATCH', 'REPLAY', 'Replay manual source file hash differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_PROVIDER_CONTEXT_MISMATCH', 'REPLAY', 'Replay provider/API retry, timeout, or HTTP context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_COVERAGE_STATE_MISMATCH', 'REPLAY', 'Replay coverage gate state or coverage count context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_COVERAGE_RATIO_MISMATCH', 'REPLAY', 'Replay coverage ratio or threshold differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_COVERAGE_REASON_MISMATCH', 'REPLAY', 'Replay coverage reason code differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_ARTIFACT_HASH_MISMATCH', 'REPLAY', 'Replay artifact hash or artifact row-count context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_SEAL_STATE_MISMATCH', 'REPLAY', 'Replay seal state differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_PUBLICATION_STATE_MISMATCH', 'REPLAY', 'Replay publication state/readability context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_PUBLICATION_VERSION_MISMATCH', 'REPLAY', 'Replay publication version differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_POINTER_TARGET_MISMATCH', 'REPLAY', 'Replay pointer target differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_POINTER_RESOLUTION_MISMATCH', 'REPLAY', 'Replay pointer resolution state differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_FALLBACK_CONTEXT_MISMATCH', 'REPLAY', 'Replay fallback context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_CORRECTION_BASELINE_MISMATCH', 'REPLAY', 'Replay correction baseline or candidate publication context differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_FINAL_STATUS_MISMATCH', 'REPLAY', 'Replay final terminal or publishability state differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_FINAL_REASON_CODE_MISMATCH', 'REPLAY', 'Replay final reason code or reason-code counts differ between expected proof and actual proof.', 'HARD', 1),
('REPLAY_LINEAGE_MISMATCH', 'REPLAY', 'Replay lineage chain differs between expected proof and actual proof.', 'HARD', 1),
('REPLAY_UNEXPECTED_SUCCESS', 'REPLAY', 'Replay produced a success-looking result when the expected proof required failure or degrade.', 'HARD', 1),
('REPLAY_UNEXPECTED_FAILURE', 'REPLAY', 'Replay produced failure when the expected proof required a successful deterministic match.', 'HARD', 1),
('REPLAY_NON_DETERMINISTIC_OUTPUT', 'REPLAY', 'Replay output contains a deterministic-field mismatch not covered by a more specific replay reason code.', 'HARD', 1)
ON DUPLICATE KEY UPDATE
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `severity` = VALUES(`severity`),
  `is_active` = VALUES(`is_active`);