<?php

require_once __DIR__.'/MarketDataOperationsTraceabilitySpec.php';

/**
 * `MD-B19` proof map.
 *
 * 743 required predicates across 37 families. The family of a predicate is decided by the
 * structure of its own owner contract -- for `MD-S075` the artifact heading it sits under, for
 * `MD-S063` the evidence pack, elsewhere the owning contract and section -- and never by matching
 * words in the predicate text. `F-MD-B18-A001-001` measured what the latter produces: 23 of 121
 * predicates in a family no keyword had chosen, and earlier branches stealing from later ones.
 *
 * `GUARDS` is deliberately incomplete at this point in the attempt. A family with no guard is a
 * measured gap the readiness gate reports by name; it is not a family that passes by default.
 */
final class MarketDataOperationsProofSpec
{
    public const STAGE = 'MD-B19';

    public const ATTEMPT = 'MD-B19-A001';

    public const BASELINE = 'MD-B19-A001-BL001';

    public const CI = 'CI-MD-B19-A001-001';

    public const EXPECTED_DENOMINATOR = 743;

    /**
     * Expected size of each family. A re-bucketing that keeps the total at 743 changes these.
     *
     * @var array<string,int>
     */
    public const FAMILY_EXPECTED_COUNTS = [
        'activation_boundary' => 8,
        'admissibility_boundary' => 3,
        'allowed_source_modes' => 2,
        'archived_executed_evidence' => 34,
        'artifact_anomaly_report' => 8,
        'artifact_correction_evidence' => 20,
        'artifact_cross_cutting_rules' => 7,
        'artifact_eligibility_export' => 9,
        'artifact_invalid_bars_export' => 9,
        'artifact_publication_manifest' => 33,
        'artifact_replay_result' => 32,
        'artifact_replay_state_pair' => 32,
        'artifact_run_event_summary' => 18,
        'artifact_run_summary' => 52,
        'artifact_set_and_categories' => 15,
        'artifact_source_attempt_telemetry' => 29,
        'audit_pack_core_rules' => 19,
        'audit_pack_correction' => 22,
        'audit_pack_replay' => 21,
        'audit_pack_run' => 29,
        'commands_and_runbook' => 17,
        'cross_contract_alignment' => 25,
        'executed_run_admission' => 21,
        'executed_run_evidence_pack' => 32,
        'freshness_and_slo' => 35,
        'incident_classification' => 18,
        'observability_minimum' => 19,
        'operator_decision_trees' => 43,
        'ownership_and_recovery' => 27,
        'range_window_acquisition' => 20,
        'range_window_checkpoint_resume' => 13,
        'range_window_warmup_calendar' => 8,
        'release_gates' => 12,
        'reprocess_and_impact_amendments' => 7,
        'resumable_backfill' => 17,
        'retention_and_maintenance' => 4,
        'scheduling_and_locking' => 23,
    ];

    /**
     * Explicit reviewed `rule_id => family`. Every required row appears exactly once and an
     * unmapped row throws, because a default is how a predicate acquires a proof nobody chose.
     *
     * @var array<string,string>
     */
    public const RULE_FAMILIES = [
        // -- activation_boundary (8)
        'MD-S029-R0073' => 'activation_boundary',
        'MD-S029-R0074' => 'activation_boundary',
        'MD-S029-R0075' => 'activation_boundary',
        'MD-S029-R0076' => 'activation_boundary',
        'MD-S029-R0102' => 'activation_boundary',
        'MD-S029-R0193' => 'activation_boundary',
        'MD-S056-R0042' => 'activation_boundary',
        'MD-S056-R0045' => 'activation_boundary',
        // -- admissibility_boundary (3)
        'MD-S008-R0077' => 'admissibility_boundary',
        'MD-S023-R0048' => 'admissibility_boundary',
        'MD-S023-R0071' => 'admissibility_boundary',
        // -- allowed_source_modes (2)
        'MD-S053-R0029' => 'allowed_source_modes',
        'MD-S053-R0030' => 'allowed_source_modes',
        // -- archived_executed_evidence (34)
        'MD-S062-R0006' => 'archived_executed_evidence',
        'MD-S062-R0007' => 'archived_executed_evidence',
        'MD-S062-R0008' => 'archived_executed_evidence',
        'MD-S062-R0009' => 'archived_executed_evidence',
        'MD-S062-R0010' => 'archived_executed_evidence',
        'MD-S062-R0011' => 'archived_executed_evidence',
        'MD-S062-R0013' => 'archived_executed_evidence',
        'MD-S062-R0014' => 'archived_executed_evidence',
        'MD-S062-R0015' => 'archived_executed_evidence',
        'MD-S062-R0016' => 'archived_executed_evidence',
        'MD-S062-R0017' => 'archived_executed_evidence',
        'MD-S062-R0018' => 'archived_executed_evidence',
        'MD-S062-R0020' => 'archived_executed_evidence',
        'MD-S062-R0021' => 'archived_executed_evidence',
        'MD-S062-R0022' => 'archived_executed_evidence',
        'MD-S062-R0023' => 'archived_executed_evidence',
        'MD-S062-R0024' => 'archived_executed_evidence',
        'MD-S062-R0025' => 'archived_executed_evidence',
        'MD-S062-R0027' => 'archived_executed_evidence',
        'MD-S062-R0028' => 'archived_executed_evidence',
        'MD-S062-R0029' => 'archived_executed_evidence',
        'MD-S062-R0030' => 'archived_executed_evidence',
        'MD-S062-R0031' => 'archived_executed_evidence',
        'MD-S062-R0033' => 'archived_executed_evidence',
        'MD-S062-R0034' => 'archived_executed_evidence',
        'MD-S062-R0035' => 'archived_executed_evidence',
        'MD-S062-R0036' => 'archived_executed_evidence',
        'MD-S062-R0038' => 'archived_executed_evidence',
        'MD-S062-R0039' => 'archived_executed_evidence',
        'MD-S062-R0040' => 'archived_executed_evidence',
        'MD-S062-R0041' => 'archived_executed_evidence',
        'MD-S062-R0042' => 'archived_executed_evidence',
        'MD-S062-R0043' => 'archived_executed_evidence',
        'MD-S062-R0061' => 'archived_executed_evidence',
        // -- artifact_anomaly_report (8)
        'MD-S075-R0160' => 'artifact_anomaly_report',
        'MD-S075-R0161' => 'artifact_anomaly_report',
        'MD-S075-R0162' => 'artifact_anomaly_report',
        'MD-S075-R0163' => 'artifact_anomaly_report',
        'MD-S075-R0164' => 'artifact_anomaly_report',
        'MD-S075-R0165' => 'artifact_anomaly_report',
        'MD-S075-R0172' => 'artifact_anomaly_report',
        'MD-S075-R0173' => 'artifact_anomaly_report',
        // -- artifact_correction_evidence (20)
        'MD-S075-R0208' => 'artifact_correction_evidence',
        'MD-S075-R0209' => 'artifact_correction_evidence',
        'MD-S075-R0210' => 'artifact_correction_evidence',
        'MD-S075-R0211' => 'artifact_correction_evidence',
        'MD-S075-R0212' => 'artifact_correction_evidence',
        'MD-S075-R0213' => 'artifact_correction_evidence',
        'MD-S075-R0214' => 'artifact_correction_evidence',
        'MD-S075-R0215' => 'artifact_correction_evidence',
        'MD-S075-R0216' => 'artifact_correction_evidence',
        'MD-S075-R0217' => 'artifact_correction_evidence',
        'MD-S075-R0218' => 'artifact_correction_evidence',
        'MD-S075-R0219' => 'artifact_correction_evidence',
        'MD-S075-R0220' => 'artifact_correction_evidence',
        'MD-S075-R0221' => 'artifact_correction_evidence',
        'MD-S075-R0222' => 'artifact_correction_evidence',
        'MD-S075-R0223' => 'artifact_correction_evidence',
        'MD-S075-R0224' => 'artifact_correction_evidence',
        'MD-S075-R0225' => 'artifact_correction_evidence',
        'MD-S075-R0226' => 'artifact_correction_evidence',
        'MD-S075-R0227' => 'artifact_correction_evidence',
        // -- artifact_cross_cutting_rules (7)
        'MD-S075-R0004' => 'artifact_cross_cutting_rules',
        'MD-S075-R0297' => 'artifact_cross_cutting_rules',
        'MD-S075-R0298' => 'artifact_cross_cutting_rules',
        'MD-S075-R0300' => 'artifact_cross_cutting_rules',
        'MD-S075-R0301' => 'artifact_cross_cutting_rules',
        'MD-S075-R0302' => 'artifact_cross_cutting_rules',
        'MD-S075-R0309' => 'artifact_cross_cutting_rules',
        // -- artifact_eligibility_export (9)
        'MD-S075-R0133' => 'artifact_eligibility_export',
        'MD-S075-R0134' => 'artifact_eligibility_export',
        'MD-S075-R0135' => 'artifact_eligibility_export',
        'MD-S075-R0136' => 'artifact_eligibility_export',
        'MD-S075-R0137' => 'artifact_eligibility_export',
        'MD-S075-R0138' => 'artifact_eligibility_export',
        'MD-S075-R0143' => 'artifact_eligibility_export',
        'MD-S075-R0144' => 'artifact_eligibility_export',
        'MD-S075-R0145' => 'artifact_eligibility_export',
        // -- artifact_invalid_bars_export (9)
        'MD-S075-R0147' => 'artifact_invalid_bars_export',
        'MD-S075-R0148' => 'artifact_invalid_bars_export',
        'MD-S075-R0149' => 'artifact_invalid_bars_export',
        'MD-S075-R0150' => 'artifact_invalid_bars_export',
        'MD-S075-R0151' => 'artifact_invalid_bars_export',
        'MD-S075-R0152' => 'artifact_invalid_bars_export',
        'MD-S075-R0156' => 'artifact_invalid_bars_export',
        'MD-S075-R0157' => 'artifact_invalid_bars_export',
        'MD-S075-R0158' => 'artifact_invalid_bars_export',
        // -- artifact_publication_manifest (33)
        'MD-S075-R0079' => 'artifact_publication_manifest',
        'MD-S075-R0080' => 'artifact_publication_manifest',
        'MD-S075-R0081' => 'artifact_publication_manifest',
        'MD-S075-R0082' => 'artifact_publication_manifest',
        'MD-S075-R0083' => 'artifact_publication_manifest',
        'MD-S075-R0084' => 'artifact_publication_manifest',
        'MD-S075-R0085' => 'artifact_publication_manifest',
        'MD-S075-R0086' => 'artifact_publication_manifest',
        'MD-S075-R0087' => 'artifact_publication_manifest',
        'MD-S075-R0088' => 'artifact_publication_manifest',
        'MD-S075-R0089' => 'artifact_publication_manifest',
        'MD-S075-R0090' => 'artifact_publication_manifest',
        'MD-S075-R0091' => 'artifact_publication_manifest',
        'MD-S075-R0092' => 'artifact_publication_manifest',
        'MD-S075-R0093' => 'artifact_publication_manifest',
        'MD-S075-R0094' => 'artifact_publication_manifest',
        'MD-S075-R0095' => 'artifact_publication_manifest',
        'MD-S075-R0096' => 'artifact_publication_manifest',
        'MD-S075-R0097' => 'artifact_publication_manifest',
        'MD-S075-R0098' => 'artifact_publication_manifest',
        'MD-S075-R0099' => 'artifact_publication_manifest',
        'MD-S075-R0100' => 'artifact_publication_manifest',
        'MD-S075-R0101' => 'artifact_publication_manifest',
        'MD-S075-R0102' => 'artifact_publication_manifest',
        'MD-S075-R0103' => 'artifact_publication_manifest',
        'MD-S075-R0104' => 'artifact_publication_manifest',
        'MD-S075-R0105' => 'artifact_publication_manifest',
        'MD-S075-R0106' => 'artifact_publication_manifest',
        'MD-S075-R0107' => 'artifact_publication_manifest',
        'MD-S075-R0108' => 'artifact_publication_manifest',
        'MD-S075-R0109' => 'artifact_publication_manifest',
        'MD-S075-R0110' => 'artifact_publication_manifest',
        'MD-S075-R0111' => 'artifact_publication_manifest',
        // -- artifact_replay_result (32)
        'MD-S075-R0231' => 'artifact_replay_result',
        'MD-S075-R0232' => 'artifact_replay_result',
        'MD-S075-R0233' => 'artifact_replay_result',
        'MD-S075-R0234' => 'artifact_replay_result',
        'MD-S075-R0235' => 'artifact_replay_result',
        'MD-S075-R0236' => 'artifact_replay_result',
        'MD-S075-R0237' => 'artifact_replay_result',
        'MD-S075-R0238' => 'artifact_replay_result',
        'MD-S075-R0239' => 'artifact_replay_result',
        'MD-S075-R0240' => 'artifact_replay_result',
        'MD-S075-R0241' => 'artifact_replay_result',
        'MD-S075-R0242' => 'artifact_replay_result',
        'MD-S075-R0243' => 'artifact_replay_result',
        'MD-S075-R0244' => 'artifact_replay_result',
        'MD-S075-R0245' => 'artifact_replay_result',
        'MD-S075-R0246' => 'artifact_replay_result',
        'MD-S075-R0247' => 'artifact_replay_result',
        'MD-S075-R0248' => 'artifact_replay_result',
        'MD-S075-R0249' => 'artifact_replay_result',
        'MD-S075-R0250' => 'artifact_replay_result',
        'MD-S075-R0251' => 'artifact_replay_result',
        'MD-S075-R0252' => 'artifact_replay_result',
        'MD-S075-R0253' => 'artifact_replay_result',
        'MD-S075-R0254' => 'artifact_replay_result',
        'MD-S075-R0255' => 'artifact_replay_result',
        'MD-S075-R0256' => 'artifact_replay_result',
        'MD-S075-R0257' => 'artifact_replay_result',
        'MD-S075-R0258' => 'artifact_replay_result',
        'MD-S075-R0259' => 'artifact_replay_result',
        'MD-S075-R0260' => 'artifact_replay_result',
        'MD-S075-R0261' => 'artifact_replay_result',
        'MD-S075-R0262' => 'artifact_replay_result',
        // -- artifact_replay_state_pair (32)
        'MD-S075-R0264' => 'artifact_replay_state_pair',
        'MD-S075-R0265' => 'artifact_replay_state_pair',
        'MD-S075-R0266' => 'artifact_replay_state_pair',
        'MD-S075-R0267' => 'artifact_replay_state_pair',
        'MD-S075-R0268' => 'artifact_replay_state_pair',
        'MD-S075-R0269' => 'artifact_replay_state_pair',
        'MD-S075-R0270' => 'artifact_replay_state_pair',
        'MD-S075-R0271' => 'artifact_replay_state_pair',
        'MD-S075-R0272' => 'artifact_replay_state_pair',
        'MD-S075-R0273' => 'artifact_replay_state_pair',
        'MD-S075-R0274' => 'artifact_replay_state_pair',
        'MD-S075-R0275' => 'artifact_replay_state_pair',
        'MD-S075-R0276' => 'artifact_replay_state_pair',
        'MD-S075-R0277' => 'artifact_replay_state_pair',
        'MD-S075-R0278' => 'artifact_replay_state_pair',
        'MD-S075-R0279' => 'artifact_replay_state_pair',
        'MD-S075-R0281' => 'artifact_replay_state_pair',
        'MD-S075-R0282' => 'artifact_replay_state_pair',
        'MD-S075-R0283' => 'artifact_replay_state_pair',
        'MD-S075-R0284' => 'artifact_replay_state_pair',
        'MD-S075-R0285' => 'artifact_replay_state_pair',
        'MD-S075-R0286' => 'artifact_replay_state_pair',
        'MD-S075-R0287' => 'artifact_replay_state_pair',
        'MD-S075-R0288' => 'artifact_replay_state_pair',
        'MD-S075-R0289' => 'artifact_replay_state_pair',
        'MD-S075-R0290' => 'artifact_replay_state_pair',
        'MD-S075-R0291' => 'artifact_replay_state_pair',
        'MD-S075-R0292' => 'artifact_replay_state_pair',
        'MD-S075-R0293' => 'artifact_replay_state_pair',
        'MD-S075-R0294' => 'artifact_replay_state_pair',
        'MD-S075-R0295' => 'artifact_replay_state_pair',
        'MD-S075-R0296' => 'artifact_replay_state_pair',
        // -- artifact_run_event_summary (18)
        'MD-S075-R0114' => 'artifact_run_event_summary',
        'MD-S075-R0115' => 'artifact_run_event_summary',
        'MD-S075-R0116' => 'artifact_run_event_summary',
        'MD-S075-R0117' => 'artifact_run_event_summary',
        'MD-S075-R0118' => 'artifact_run_event_summary',
        'MD-S075-R0119' => 'artifact_run_event_summary',
        'MD-S075-R0120' => 'artifact_run_event_summary',
        'MD-S075-R0121' => 'artifact_run_event_summary',
        'MD-S075-R0122' => 'artifact_run_event_summary',
        'MD-S075-R0123' => 'artifact_run_event_summary',
        'MD-S075-R0124' => 'artifact_run_event_summary',
        'MD-S075-R0125' => 'artifact_run_event_summary',
        'MD-S075-R0126' => 'artifact_run_event_summary',
        'MD-S075-R0127' => 'artifact_run_event_summary',
        'MD-S075-R0128' => 'artifact_run_event_summary',
        'MD-S075-R0129' => 'artifact_run_event_summary',
        'MD-S075-R0130' => 'artifact_run_event_summary',
        'MD-S075-R0131' => 'artifact_run_event_summary',
        // -- artifact_run_summary (52)
        'MD-S075-R0025' => 'artifact_run_summary',
        'MD-S075-R0026' => 'artifact_run_summary',
        'MD-S075-R0027' => 'artifact_run_summary',
        'MD-S075-R0028' => 'artifact_run_summary',
        'MD-S075-R0029' => 'artifact_run_summary',
        'MD-S075-R0030' => 'artifact_run_summary',
        'MD-S075-R0031' => 'artifact_run_summary',
        'MD-S075-R0032' => 'artifact_run_summary',
        'MD-S075-R0033' => 'artifact_run_summary',
        'MD-S075-R0034' => 'artifact_run_summary',
        'MD-S075-R0035' => 'artifact_run_summary',
        'MD-S075-R0036' => 'artifact_run_summary',
        'MD-S075-R0037' => 'artifact_run_summary',
        'MD-S075-R0038' => 'artifact_run_summary',
        'MD-S075-R0039' => 'artifact_run_summary',
        'MD-S075-R0040' => 'artifact_run_summary',
        'MD-S075-R0041' => 'artifact_run_summary',
        'MD-S075-R0042' => 'artifact_run_summary',
        'MD-S075-R0043' => 'artifact_run_summary',
        'MD-S075-R0044' => 'artifact_run_summary',
        'MD-S075-R0045' => 'artifact_run_summary',
        'MD-S075-R0046' => 'artifact_run_summary',
        'MD-S075-R0047' => 'artifact_run_summary',
        'MD-S075-R0048' => 'artifact_run_summary',
        'MD-S075-R0049' => 'artifact_run_summary',
        'MD-S075-R0050' => 'artifact_run_summary',
        'MD-S075-R0051' => 'artifact_run_summary',
        'MD-S075-R0052' => 'artifact_run_summary',
        'MD-S075-R0053' => 'artifact_run_summary',
        'MD-S075-R0054' => 'artifact_run_summary',
        'MD-S075-R0055' => 'artifact_run_summary',
        'MD-S075-R0056' => 'artifact_run_summary',
        'MD-S075-R0057' => 'artifact_run_summary',
        'MD-S075-R0058' => 'artifact_run_summary',
        'MD-S075-R0059' => 'artifact_run_summary',
        'MD-S075-R0060' => 'artifact_run_summary',
        'MD-S075-R0061' => 'artifact_run_summary',
        'MD-S075-R0062' => 'artifact_run_summary',
        'MD-S075-R0063' => 'artifact_run_summary',
        'MD-S075-R0064' => 'artifact_run_summary',
        'MD-S075-R0065' => 'artifact_run_summary',
        'MD-S075-R0066' => 'artifact_run_summary',
        'MD-S075-R0067' => 'artifact_run_summary',
        'MD-S075-R0068' => 'artifact_run_summary',
        'MD-S075-R0069' => 'artifact_run_summary',
        'MD-S075-R0070' => 'artifact_run_summary',
        'MD-S075-R0071' => 'artifact_run_summary',
        'MD-S075-R0072' => 'artifact_run_summary',
        'MD-S075-R0073' => 'artifact_run_summary',
        'MD-S075-R0074' => 'artifact_run_summary',
        'MD-S075-R0075' => 'artifact_run_summary',
        'MD-S075-R0076' => 'artifact_run_summary',
        // -- artifact_set_and_categories (15)
        'MD-S075-R0006' => 'artifact_set_and_categories',
        'MD-S075-R0007' => 'artifact_set_and_categories',
        'MD-S075-R0008' => 'artifact_set_and_categories',
        'MD-S075-R0009' => 'artifact_set_and_categories',
        'MD-S075-R0011' => 'artifact_set_and_categories',
        'MD-S075-R0012' => 'artifact_set_and_categories',
        'MD-S075-R0013' => 'artifact_set_and_categories',
        'MD-S075-R0014' => 'artifact_set_and_categories',
        'MD-S075-R0015' => 'artifact_set_and_categories',
        'MD-S075-R0016' => 'artifact_set_and_categories',
        'MD-S075-R0018' => 'artifact_set_and_categories',
        'MD-S075-R0019' => 'artifact_set_and_categories',
        'MD-S075-R0020' => 'artifact_set_and_categories',
        'MD-S075-R0021' => 'artifact_set_and_categories',
        'MD-S075-R0022' => 'artifact_set_and_categories',
        // -- artifact_source_attempt_telemetry (29)
        'MD-S075-R0176' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0177' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0178' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0179' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0180' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0181' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0182' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0183' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0184' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0185' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0186' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0187' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0188' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0189' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0190' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0191' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0192' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0193' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0194' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0195' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0196' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0197' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0198' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0199' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0200' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0201' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0202' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0203' => 'artifact_source_attempt_telemetry',
        'MD-S075-R0204' => 'artifact_source_attempt_telemetry',
        // -- audit_pack_core_rules (19)
        'MD-S063-R0002' => 'audit_pack_core_rules',
        'MD-S063-R0003' => 'audit_pack_core_rules',
        'MD-S063-R0004' => 'audit_pack_core_rules',
        'MD-S063-R0005' => 'audit_pack_core_rules',
        'MD-S063-R0007' => 'audit_pack_core_rules',
        'MD-S063-R0008' => 'audit_pack_core_rules',
        'MD-S063-R0009' => 'audit_pack_core_rules',
        'MD-S063-R0010' => 'audit_pack_core_rules',
        'MD-S063-R0011' => 'audit_pack_core_rules',
        'MD-S063-R0012' => 'audit_pack_core_rules',
        'MD-S063-R0014' => 'audit_pack_core_rules',
        'MD-S063-R0015' => 'audit_pack_core_rules',
        'MD-S063-R0016' => 'audit_pack_core_rules',
        'MD-S063-R0151' => 'audit_pack_core_rules',
        'MD-S063-R0152' => 'audit_pack_core_rules',
        'MD-S063-R0153' => 'audit_pack_core_rules',
        'MD-S063-R0154' => 'audit_pack_core_rules',
        'MD-S063-R0155' => 'audit_pack_core_rules',
        'MD-S063-R0168' => 'audit_pack_core_rules',
        // -- audit_pack_correction (22)
        'MD-S063-R0057' => 'audit_pack_correction',
        'MD-S063-R0059' => 'audit_pack_correction',
        'MD-S063-R0060' => 'audit_pack_correction',
        'MD-S063-R0061' => 'audit_pack_correction',
        'MD-S063-R0062' => 'audit_pack_correction',
        'MD-S063-R0063' => 'audit_pack_correction',
        'MD-S063-R0064' => 'audit_pack_correction',
        'MD-S063-R0065' => 'audit_pack_correction',
        'MD-S063-R0066' => 'audit_pack_correction',
        'MD-S063-R0067' => 'audit_pack_correction',
        'MD-S063-R0068' => 'audit_pack_correction',
        'MD-S063-R0069' => 'audit_pack_correction',
        'MD-S063-R0070' => 'audit_pack_correction',
        'MD-S063-R0071' => 'audit_pack_correction',
        'MD-S063-R0072' => 'audit_pack_correction',
        'MD-S063-R0073' => 'audit_pack_correction',
        'MD-S063-R0074' => 'audit_pack_correction',
        'MD-S063-R0075' => 'audit_pack_correction',
        'MD-S063-R0076' => 'audit_pack_correction',
        'MD-S063-R0077' => 'audit_pack_correction',
        'MD-S063-R0078' => 'audit_pack_correction',
        'MD-S063-R0079' => 'audit_pack_correction',
        // -- audit_pack_replay (21)
        'MD-S063-R0102' => 'audit_pack_replay',
        'MD-S063-R0104' => 'audit_pack_replay',
        'MD-S063-R0105' => 'audit_pack_replay',
        'MD-S063-R0106' => 'audit_pack_replay',
        'MD-S063-R0107' => 'audit_pack_replay',
        'MD-S063-R0108' => 'audit_pack_replay',
        'MD-S063-R0109' => 'audit_pack_replay',
        'MD-S063-R0110' => 'audit_pack_replay',
        'MD-S063-R0111' => 'audit_pack_replay',
        'MD-S063-R0112' => 'audit_pack_replay',
        'MD-S063-R0113' => 'audit_pack_replay',
        'MD-S063-R0114' => 'audit_pack_replay',
        'MD-S063-R0115' => 'audit_pack_replay',
        'MD-S063-R0116' => 'audit_pack_replay',
        'MD-S063-R0117' => 'audit_pack_replay',
        'MD-S063-R0118' => 'audit_pack_replay',
        'MD-S063-R0119' => 'audit_pack_replay',
        'MD-S063-R0120' => 'audit_pack_replay',
        'MD-S063-R0121' => 'audit_pack_replay',
        'MD-S063-R0122' => 'audit_pack_replay',
        'MD-S063-R0123' => 'audit_pack_replay',
        // -- audit_pack_run (29)
        'MD-S063-R0017' => 'audit_pack_run',
        'MD-S063-R0019' => 'audit_pack_run',
        'MD-S063-R0020' => 'audit_pack_run',
        'MD-S063-R0021' => 'audit_pack_run',
        'MD-S063-R0022' => 'audit_pack_run',
        'MD-S063-R0023' => 'audit_pack_run',
        'MD-S063-R0024' => 'audit_pack_run',
        'MD-S063-R0025' => 'audit_pack_run',
        'MD-S063-R0026' => 'audit_pack_run',
        'MD-S063-R0027' => 'audit_pack_run',
        'MD-S063-R0028' => 'audit_pack_run',
        'MD-S063-R0029' => 'audit_pack_run',
        'MD-S063-R0030' => 'audit_pack_run',
        'MD-S063-R0031' => 'audit_pack_run',
        'MD-S063-R0032' => 'audit_pack_run',
        'MD-S063-R0033' => 'audit_pack_run',
        'MD-S063-R0034' => 'audit_pack_run',
        'MD-S063-R0035' => 'audit_pack_run',
        'MD-S063-R0036' => 'audit_pack_run',
        'MD-S063-R0037' => 'audit_pack_run',
        'MD-S063-R0038' => 'audit_pack_run',
        'MD-S063-R0039' => 'audit_pack_run',
        'MD-S063-R0040' => 'audit_pack_run',
        'MD-S063-R0041' => 'audit_pack_run',
        'MD-S063-R0042' => 'audit_pack_run',
        'MD-S063-R0043' => 'audit_pack_run',
        'MD-S063-R0044' => 'audit_pack_run',
        'MD-S063-R0045' => 'audit_pack_run',
        'MD-S063-R0046' => 'audit_pack_run',
        // -- commands_and_runbook (17)
        'MD-S036-R0013' => 'commands_and_runbook',
        'MD-S064-R0001' => 'commands_and_runbook',
        'MD-S064-R0002' => 'commands_and_runbook',
        'MD-S064-R0003' => 'commands_and_runbook',
        'MD-S064-R0004' => 'commands_and_runbook',
        'MD-S064-R0005' => 'commands_and_runbook',
        'MD-S064-R0006' => 'commands_and_runbook',
        'MD-S064-R0007' => 'commands_and_runbook',
        'MD-S064-R0008' => 'commands_and_runbook',
        'MD-S064-R0009' => 'commands_and_runbook',
        'MD-S064-R0010' => 'commands_and_runbook',
        'MD-S064-R0011' => 'commands_and_runbook',
        'MD-S064-R0012' => 'commands_and_runbook',
        'MD-S064-R0013' => 'commands_and_runbook',
        'MD-S064-R0014' => 'commands_and_runbook',
        'MD-S064-R0015' => 'commands_and_runbook',
        'MD-S064-R0016' => 'commands_and_runbook',
        // -- cross_contract_alignment (25)
        'MD-S062-R0056' => 'cross_contract_alignment',
        'MD-S062-R0057' => 'cross_contract_alignment',
        'MD-S062-R0058' => 'cross_contract_alignment',
        'MD-S062-R0059' => 'cross_contract_alignment',
        'MD-S062-R0060' => 'cross_contract_alignment',
        'MD-S063-R0163' => 'cross_contract_alignment',
        'MD-S063-R0164' => 'cross_contract_alignment',
        'MD-S063-R0165' => 'cross_contract_alignment',
        'MD-S063-R0166' => 'cross_contract_alignment',
        'MD-S063-R0167' => 'cross_contract_alignment',
        'MD-S068-R0027' => 'cross_contract_alignment',
        'MD-S068-R0028' => 'cross_contract_alignment',
        'MD-S068-R0029' => 'cross_contract_alignment',
        'MD-S071-R0045' => 'cross_contract_alignment',
        'MD-S071-R0046' => 'cross_contract_alignment',
        'MD-S071-R0047' => 'cross_contract_alignment',
        'MD-S075-R0304' => 'cross_contract_alignment',
        'MD-S075-R0305' => 'cross_contract_alignment',
        'MD-S075-R0306' => 'cross_contract_alignment',
        'MD-S075-R0307' => 'cross_contract_alignment',
        'MD-S075-R0308' => 'cross_contract_alignment',
        'MD-S076-R0049' => 'cross_contract_alignment',
        'MD-S076-R0050' => 'cross_contract_alignment',
        'MD-S076-R0051' => 'cross_contract_alignment',
        'MD-S076-R0052' => 'cross_contract_alignment',
        // -- executed_run_admission (21)
        'MD-S068-R0002' => 'executed_run_admission',
        'MD-S068-R0005' => 'executed_run_admission',
        'MD-S068-R0006' => 'executed_run_admission',
        'MD-S068-R0008' => 'executed_run_admission',
        'MD-S068-R0009' => 'executed_run_admission',
        'MD-S068-R0010' => 'executed_run_admission',
        'MD-S068-R0011' => 'executed_run_admission',
        'MD-S068-R0012' => 'executed_run_admission',
        'MD-S068-R0014' => 'executed_run_admission',
        'MD-S068-R0015' => 'executed_run_admission',
        'MD-S068-R0016' => 'executed_run_admission',
        'MD-S068-R0023' => 'executed_run_admission',
        'MD-S068-R0024' => 'executed_run_admission',
        'MD-S068-R0025' => 'executed_run_admission',
        'MD-S068-R0030' => 'executed_run_admission',
        'MD-S068-R0031' => 'executed_run_admission',
        'MD-S068-R0032' => 'executed_run_admission',
        'MD-S068-R0033' => 'executed_run_admission',
        'MD-S068-R0034' => 'executed_run_admission',
        'MD-S068-R0035' => 'executed_run_admission',
        'MD-S068-R0036' => 'executed_run_admission',
        // -- executed_run_evidence_pack (32)
        'MD-S076-R0006' => 'executed_run_evidence_pack',
        'MD-S076-R0007' => 'executed_run_evidence_pack',
        'MD-S076-R0008' => 'executed_run_evidence_pack',
        'MD-S076-R0009' => 'executed_run_evidence_pack',
        'MD-S076-R0010' => 'executed_run_evidence_pack',
        'MD-S076-R0012' => 'executed_run_evidence_pack',
        'MD-S076-R0013' => 'executed_run_evidence_pack',
        'MD-S076-R0014' => 'executed_run_evidence_pack',
        'MD-S076-R0015' => 'executed_run_evidence_pack',
        'MD-S076-R0016' => 'executed_run_evidence_pack',
        'MD-S076-R0017' => 'executed_run_evidence_pack',
        'MD-S076-R0018' => 'executed_run_evidence_pack',
        'MD-S076-R0019' => 'executed_run_evidence_pack',
        'MD-S076-R0021' => 'executed_run_evidence_pack',
        'MD-S076-R0022' => 'executed_run_evidence_pack',
        'MD-S076-R0023' => 'executed_run_evidence_pack',
        'MD-S076-R0024' => 'executed_run_evidence_pack',
        'MD-S076-R0025' => 'executed_run_evidence_pack',
        'MD-S076-R0026' => 'executed_run_evidence_pack',
        'MD-S076-R0028' => 'executed_run_evidence_pack',
        'MD-S076-R0029' => 'executed_run_evidence_pack',
        'MD-S076-R0030' => 'executed_run_evidence_pack',
        'MD-S076-R0031' => 'executed_run_evidence_pack',
        'MD-S076-R0032' => 'executed_run_evidence_pack',
        'MD-S076-R0034' => 'executed_run_evidence_pack',
        'MD-S076-R0035' => 'executed_run_evidence_pack',
        'MD-S076-R0036' => 'executed_run_evidence_pack',
        'MD-S076-R0038' => 'executed_run_evidence_pack',
        'MD-S076-R0040' => 'executed_run_evidence_pack',
        'MD-S076-R0041' => 'executed_run_evidence_pack',
        'MD-S076-R0042' => 'executed_run_evidence_pack',
        'MD-S076-R0053' => 'executed_run_evidence_pack',
        // -- freshness_and_slo (35)
        'MD-S072-R0001' => 'freshness_and_slo',
        'MD-S072-R0003' => 'freshness_and_slo',
        'MD-S072-R0004' => 'freshness_and_slo',
        'MD-S072-R0005' => 'freshness_and_slo',
        'MD-S072-R0006' => 'freshness_and_slo',
        'MD-S072-R0007' => 'freshness_and_slo',
        'MD-S072-R0008' => 'freshness_and_slo',
        'MD-S072-R0009' => 'freshness_and_slo',
        'MD-S072-R0010' => 'freshness_and_slo',
        'MD-S072-R0011' => 'freshness_and_slo',
        'MD-S072-R0013' => 'freshness_and_slo',
        'MD-S072-R0014' => 'freshness_and_slo',
        'MD-S072-R0015' => 'freshness_and_slo',
        'MD-S072-R0016' => 'freshness_and_slo',
        'MD-S072-R0017' => 'freshness_and_slo',
        'MD-S072-R0018' => 'freshness_and_slo',
        'MD-S072-R0019' => 'freshness_and_slo',
        'MD-S072-R0020' => 'freshness_and_slo',
        'MD-S072-R0021' => 'freshness_and_slo',
        'MD-S072-R0022' => 'freshness_and_slo',
        'MD-S072-R0023' => 'freshness_and_slo',
        'MD-S072-R0024' => 'freshness_and_slo',
        'MD-S072-R0025' => 'freshness_and_slo',
        'MD-S072-R0026' => 'freshness_and_slo',
        'MD-S072-R0027' => 'freshness_and_slo',
        'MD-S072-R0028' => 'freshness_and_slo',
        'MD-S072-R0029' => 'freshness_and_slo',
        'MD-S072-R0030' => 'freshness_and_slo',
        'MD-S072-R0031' => 'freshness_and_slo',
        'MD-S072-R0032' => 'freshness_and_slo',
        'MD-S072-R0033' => 'freshness_and_slo',
        'MD-S072-R0034' => 'freshness_and_slo',
        'MD-S072-R0035' => 'freshness_and_slo',
        'MD-S072-R0036' => 'freshness_and_slo',
        'MD-S072-R0037' => 'freshness_and_slo',
        // -- incident_classification (18)
        'MD-S058-R0055' => 'incident_classification',
        'MD-S069-R0001' => 'incident_classification',
        'MD-S069-R0002' => 'incident_classification',
        'MD-S069-R0003' => 'incident_classification',
        'MD-S069-R0004' => 'incident_classification',
        'MD-S069-R0005' => 'incident_classification',
        'MD-S069-R0006' => 'incident_classification',
        'MD-S069-R0007' => 'incident_classification',
        'MD-S069-R0008' => 'incident_classification',
        'MD-S069-R0009' => 'incident_classification',
        'MD-S069-R0010' => 'incident_classification',
        'MD-S069-R0011' => 'incident_classification',
        'MD-S069-R0012' => 'incident_classification',
        'MD-S069-R0013' => 'incident_classification',
        'MD-S069-R0014' => 'incident_classification',
        'MD-S069-R0015' => 'incident_classification',
        'MD-S069-R0016' => 'incident_classification',
        'MD-S069-R0017' => 'incident_classification',
        // -- observability_minimum (19)
        'MD-S070-R0002' => 'observability_minimum',
        'MD-S070-R0003' => 'observability_minimum',
        'MD-S070-R0004' => 'observability_minimum',
        'MD-S070-R0005' => 'observability_minimum',
        'MD-S070-R0006' => 'observability_minimum',
        'MD-S070-R0007' => 'observability_minimum',
        'MD-S070-R0008' => 'observability_minimum',
        'MD-S070-R0009' => 'observability_minimum',
        'MD-S070-R0010' => 'observability_minimum',
        'MD-S070-R0011' => 'observability_minimum',
        'MD-S070-R0012' => 'observability_minimum',
        'MD-S070-R0013' => 'observability_minimum',
        'MD-S070-R0014' => 'observability_minimum',
        'MD-S070-R0015' => 'observability_minimum',
        'MD-S070-R0016' => 'observability_minimum',
        'MD-S070-R0017' => 'observability_minimum',
        'MD-S070-R0018' => 'observability_minimum',
        'MD-S070-R0019' => 'observability_minimum',
        'MD-S070-R0020' => 'observability_minimum',
        // -- operator_decision_trees (43)
        'MD-S071-R0002' => 'operator_decision_trees',
        'MD-S071-R0003' => 'operator_decision_trees',
        'MD-S071-R0004' => 'operator_decision_trees',
        'MD-S071-R0005' => 'operator_decision_trees',
        'MD-S071-R0006' => 'operator_decision_trees',
        'MD-S071-R0007' => 'operator_decision_trees',
        'MD-S071-R0008' => 'operator_decision_trees',
        'MD-S071-R0009' => 'operator_decision_trees',
        'MD-S071-R0010' => 'operator_decision_trees',
        'MD-S071-R0011' => 'operator_decision_trees',
        'MD-S071-R0012' => 'operator_decision_trees',
        'MD-S071-R0013' => 'operator_decision_trees',
        'MD-S071-R0014' => 'operator_decision_trees',
        'MD-S071-R0015' => 'operator_decision_trees',
        'MD-S071-R0016' => 'operator_decision_trees',
        'MD-S071-R0017' => 'operator_decision_trees',
        'MD-S071-R0018' => 'operator_decision_trees',
        'MD-S071-R0019' => 'operator_decision_trees',
        'MD-S071-R0020' => 'operator_decision_trees',
        'MD-S071-R0021' => 'operator_decision_trees',
        'MD-S071-R0022' => 'operator_decision_trees',
        'MD-S071-R0023' => 'operator_decision_trees',
        'MD-S071-R0024' => 'operator_decision_trees',
        'MD-S071-R0025' => 'operator_decision_trees',
        'MD-S071-R0026' => 'operator_decision_trees',
        'MD-S071-R0027' => 'operator_decision_trees',
        'MD-S071-R0028' => 'operator_decision_trees',
        'MD-S071-R0029' => 'operator_decision_trees',
        'MD-S071-R0030' => 'operator_decision_trees',
        'MD-S071-R0031' => 'operator_decision_trees',
        'MD-S071-R0032' => 'operator_decision_trees',
        'MD-S071-R0033' => 'operator_decision_trees',
        'MD-S071-R0034' => 'operator_decision_trees',
        'MD-S071-R0035' => 'operator_decision_trees',
        'MD-S071-R0036' => 'operator_decision_trees',
        'MD-S071-R0037' => 'operator_decision_trees',
        'MD-S071-R0038' => 'operator_decision_trees',
        'MD-S071-R0039' => 'operator_decision_trees',
        'MD-S071-R0040' => 'operator_decision_trees',
        'MD-S071-R0041' => 'operator_decision_trees',
        'MD-S071-R0042' => 'operator_decision_trees',
        'MD-S071-R0043' => 'operator_decision_trees',
        'MD-S071-R0048' => 'operator_decision_trees',
        // -- ownership_and_recovery (27)
        'MD-S067-R0016' => 'ownership_and_recovery',
        'MD-S067-R0017' => 'ownership_and_recovery',
        'MD-S077-R0003' => 'ownership_and_recovery',
        'MD-S077-R0004' => 'ownership_and_recovery',
        'MD-S077-R0006' => 'ownership_and_recovery',
        'MD-S077-R0013' => 'ownership_and_recovery',
        'MD-S077-R0015' => 'ownership_and_recovery',
        'MD-S077-R0016' => 'ownership_and_recovery',
        'MD-S077-R0017' => 'ownership_and_recovery',
        'MD-S077-R0018' => 'ownership_and_recovery',
        'MD-S077-R0019' => 'ownership_and_recovery',
        'MD-S077-R0021' => 'ownership_and_recovery',
        'MD-S077-R0022' => 'ownership_and_recovery',
        'MD-S077-R0023' => 'ownership_and_recovery',
        'MD-S077-R0025' => 'ownership_and_recovery',
        'MD-S077-R0027' => 'ownership_and_recovery',
        'MD-S077-R0028' => 'ownership_and_recovery',
        'MD-S077-R0029' => 'ownership_and_recovery',
        'MD-S077-R0031' => 'ownership_and_recovery',
        'MD-S077-R0032' => 'ownership_and_recovery',
        'MD-S077-R0033' => 'ownership_and_recovery',
        'MD-S077-R0034' => 'ownership_and_recovery',
        'MD-S077-R0035' => 'ownership_and_recovery',
        'MD-S077-R0037' => 'ownership_and_recovery',
        'MD-S077-R0038' => 'ownership_and_recovery',
        'MD-S077-R0039' => 'ownership_and_recovery',
        'MD-S077-R0040' => 'ownership_and_recovery',
        // -- range_window_acquisition (20)
        'MD-S053-R0179' => 'range_window_acquisition',
        'MD-S053-R0180' => 'range_window_acquisition',
        'MD-S053-R0181' => 'range_window_acquisition',
        'MD-S053-R0182' => 'range_window_acquisition',
        'MD-S053-R0183' => 'range_window_acquisition',
        'MD-S053-R0185' => 'range_window_acquisition',
        'MD-S053-R0186' => 'range_window_acquisition',
        'MD-S053-R0187' => 'range_window_acquisition',
        'MD-S053-R0188' => 'range_window_acquisition',
        'MD-S053-R0189' => 'range_window_acquisition',
        'MD-S053-R0190' => 'range_window_acquisition',
        'MD-S053-R0191' => 'range_window_acquisition',
        'MD-S053-R0192' => 'range_window_acquisition',
        'MD-S053-R0193' => 'range_window_acquisition',
        'MD-S053-R0194' => 'range_window_acquisition',
        'MD-S053-R0195' => 'range_window_acquisition',
        'MD-S053-R0197' => 'range_window_acquisition',
        'MD-S053-R0198' => 'range_window_acquisition',
        'MD-S053-R0199' => 'range_window_acquisition',
        'MD-S053-R0200' => 'range_window_acquisition',
        // -- range_window_checkpoint_resume (13)
        'MD-S053-R0202' => 'range_window_checkpoint_resume',
        'MD-S053-R0204' => 'range_window_checkpoint_resume',
        'MD-S053-R0205' => 'range_window_checkpoint_resume',
        'MD-S053-R0206' => 'range_window_checkpoint_resume',
        'MD-S053-R0208' => 'range_window_checkpoint_resume',
        'MD-S053-R0209' => 'range_window_checkpoint_resume',
        'MD-S053-R0210' => 'range_window_checkpoint_resume',
        'MD-S053-R0212' => 'range_window_checkpoint_resume',
        'MD-S053-R0213' => 'range_window_checkpoint_resume',
        'MD-S053-R0214' => 'range_window_checkpoint_resume',
        'MD-S053-R0215' => 'range_window_checkpoint_resume',
        'MD-S053-R0216' => 'range_window_checkpoint_resume',
        'MD-S053-R0217' => 'range_window_checkpoint_resume',
        // -- range_window_warmup_calendar (8)
        'MD-S053-R0218' => 'range_window_warmup_calendar',
        'MD-S053-R0219' => 'range_window_warmup_calendar',
        'MD-S053-R0220' => 'range_window_warmup_calendar',
        'MD-S053-R0221' => 'range_window_warmup_calendar',
        'MD-S053-R0222' => 'range_window_warmup_calendar',
        'MD-S053-R0223' => 'range_window_warmup_calendar',
        'MD-S053-R0224' => 'range_window_warmup_calendar',
        'MD-S053-R0225' => 'range_window_warmup_calendar',
        // -- release_gates (12)
        'MD-S065-R0004' => 'release_gates',
        'MD-S073-R0002' => 'release_gates',
        'MD-S073-R0003' => 'release_gates',
        'MD-S073-R0004' => 'release_gates',
        'MD-S073-R0005' => 'release_gates',
        'MD-S073-R0006' => 'release_gates',
        'MD-S073-R0007' => 'release_gates',
        'MD-S073-R0008' => 'release_gates',
        'MD-S073-R0009' => 'release_gates',
        'MD-S073-R0010' => 'release_gates',
        'MD-S073-R0011' => 'release_gates',
        'MD-S073-R0012' => 'release_gates',
        // -- reprocess_and_impact_amendments (7)
        'MD-S075-R0315' => 'reprocess_and_impact_amendments',
        'MD-S075-R0317' => 'reprocess_and_impact_amendments',
        'MD-S075-R0319' => 'reprocess_and_impact_amendments',
        'MD-S075-R0321' => 'reprocess_and_impact_amendments',
        'MD-S075-R0322' => 'reprocess_and_impact_amendments',
        'MD-S075-R0323' => 'reprocess_and_impact_amendments',
        'MD-S075-R0324' => 'reprocess_and_impact_amendments',
        // -- resumable_backfill (17)
        'MD-S059-R0072' => 'resumable_backfill',
        'MD-S059-R0074' => 'resumable_backfill',
        'MD-S059-R0140' => 'resumable_backfill',
        'MD-S074-R0001' => 'resumable_backfill',
        'MD-S074-R0002' => 'resumable_backfill',
        'MD-S074-R0003' => 'resumable_backfill',
        'MD-S074-R0004' => 'resumable_backfill',
        'MD-S074-R0005' => 'resumable_backfill',
        'MD-S074-R0006' => 'resumable_backfill',
        'MD-S074-R0007' => 'resumable_backfill',
        'MD-S074-R0009' => 'resumable_backfill',
        'MD-S074-R0010' => 'resumable_backfill',
        'MD-S074-R0011' => 'resumable_backfill',
        'MD-S074-R0012' => 'resumable_backfill',
        'MD-S074-R0013' => 'resumable_backfill',
        'MD-S074-R0014' => 'resumable_backfill',
        'MD-S074-R0015' => 'resumable_backfill',
        // -- retention_and_maintenance (4)
        'MD-S001-R0085' => 'retention_and_maintenance',
        'MD-S001-R0087' => 'retention_and_maintenance',
        'MD-S001-R0088' => 'retention_and_maintenance',
        'MD-S082-R0018' => 'retention_and_maintenance',
        // -- scheduling_and_locking (23)
        'MD-S041-R0057' => 'scheduling_and_locking',
        'MD-S041-R0059' => 'scheduling_and_locking',
        'MD-S041-R0060' => 'scheduling_and_locking',
        'MD-S041-R0061' => 'scheduling_and_locking',
        'MD-S078-R0001' => 'scheduling_and_locking',
        'MD-S078-R0002' => 'scheduling_and_locking',
        'MD-S078-R0003' => 'scheduling_and_locking',
        'MD-S078-R0004' => 'scheduling_and_locking',
        'MD-S078-R0005' => 'scheduling_and_locking',
        'MD-S078-R0006' => 'scheduling_and_locking',
        'MD-S078-R0007' => 'scheduling_and_locking',
        'MD-S078-R0008' => 'scheduling_and_locking',
        'MD-S078-R0009' => 'scheduling_and_locking',
        'MD-S078-R0010' => 'scheduling_and_locking',
        'MD-S078-R0011' => 'scheduling_and_locking',
        'MD-S078-R0012' => 'scheduling_and_locking',
        'MD-S078-R0013' => 'scheduling_and_locking',
        'MD-S078-R0014' => 'scheduling_and_locking',
        'MD-S078-R0015' => 'scheduling_and_locking',
        'MD-S078-R0016' => 'scheduling_and_locking',
        'MD-S078-R0017' => 'scheduling_and_locking',
        'MD-S078-R0018' => 'scheduling_and_locking',
        'MD-S078-R0019' => 'scheduling_and_locking',
    ];

    /**
     * Implementation surface per family. Guards are assigned as they are written and verified;
     * an empty pair is reported by the readiness gate as an unproven family.
     *
     * @return array<string,array<string,mixed>>
     */
    public static function families(): array
    {
        return [
            'activation_boundary' => [
                'owner' => 'MD-B19:activation-boundary',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataReadinessService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'admissibility_boundary' => [
                'owner' => 'MD-B19:admissibility-boundary',
                'implementation' => [
                    'app/Application/MarketData/Services/EodBarsIngestService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'allowed_source_modes' => [
                'owner' => 'MD-B19:allowed-source-modes',
                'implementation' => [
                    'app/Application/MarketData/Services/EodBarsIngestService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'archived_executed_evidence' => [
                'owner' => 'MD-B19:archived-executed-evidence',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_anomaly_report' => [
                'owner' => 'MD-B19:artifact-anomaly-report',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_correction_evidence' => [
                'owner' => 'MD-B19:artifact-correction-evidence',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                    'app/Infrastructure/Persistence/MarketData/EodCorrectionRepository.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_cross_cutting_rules' => [
                'owner' => 'MD-B19:artifact-cross-cutting-rules',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_eligibility_export' => [
                'owner' => 'MD-B19:artifact-eligibility-export',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_invalid_bars_export' => [
                'owner' => 'MD-B19:artifact-invalid-bars-export',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_publication_manifest' => [
                'owner' => 'MD-B19:artifact-publication-manifest',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                    'app/Infrastructure/Persistence/MarketData/EodPublicationRepository.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_replay_result' => [
                'owner' => 'MD-B19:artifact-replay-result',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                    'app/Infrastructure/Persistence/MarketData/ReplayResultRepository.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_replay_state_pair' => [
                'owner' => 'MD-B19:artifact-replay-state-pair',
                'implementation' => [
                    'app/Application/MarketData/Services/ReplayVerificationService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_run_event_summary' => [
                'owner' => 'MD-B19:artifact-run-event-summary',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                    'app/Infrastructure/Persistence/MarketData/EodEvidenceRepository.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_run_summary' => [
                'owner' => 'MD-B19:artifact-run-summary',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => ['tests/Unit/MarketData/B19RunSummaryArtifactContractTest.php', 'test_the_exported_run_summary_carries_every_minimum_field_the_contract_names'],
                'negative' => ['tests/Unit/MarketData/B19RunSummaryArtifactContractTest.php', 'test_a_held_run_is_not_summarised_as_readable'],
            ],
            'artifact_set_and_categories' => [
                'owner' => 'MD-B19:artifact-set-and-categories',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'artifact_source_attempt_telemetry' => [
                'owner' => 'MD-B19:artifact-source-attempt-telemetry',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'audit_pack_core_rules' => [
                'owner' => 'MD-B19:audit-pack-core-rules',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'audit_pack_correction' => [
                'owner' => 'MD-B19:audit-pack-correction',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'audit_pack_replay' => [
                'owner' => 'MD-B19:audit-pack-replay',
                'implementation' => [
                    'app/Application/MarketData/Services/ReplayVerificationService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'audit_pack_run' => [
                'owner' => 'MD-B19:audit-pack-run',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'commands_and_runbook' => [
                'owner' => 'MD-B19:commands-and-runbook',
                'implementation' => [
                    'app/Console/Commands/MarketData',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'cross_contract_alignment' => [
                'owner' => 'MD-B19:cross-contract-alignment',
                'implementation' => [
                    'docs/market_data/authority/strategy/ops',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'executed_run_admission' => [
                'owner' => 'MD-B19:executed-run-admission',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'executed_run_evidence_pack' => [
                'owner' => 'MD-B19:executed-run-evidence-pack',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataEvidenceExportService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'freshness_and_slo' => [
                'owner' => 'MD-B19:freshness-and-slo',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataReadinessService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'incident_classification' => [
                'owner' => 'MD-B19:incident-classification',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataPipelineService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'observability_minimum' => [
                'owner' => 'MD-B19:observability-minimum',
                'implementation' => [
                    'app/Infrastructure/Persistence/MarketData/EodEvidenceRepository.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'operator_decision_trees' => [
                'owner' => 'MD-B19:operator-decision-trees',
                'implementation' => [
                    'app/Console/Commands/MarketData',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'ownership_and_recovery' => [
                'owner' => 'MD-B19:ownership-and-recovery',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataPipelineService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'range_window_acquisition' => [
                'owner' => 'MD-B19:range-window-acquisition',
                'implementation' => [
                    'app/Application/MarketData/Services/ApiBackfillRangeAcquisitionService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'range_window_checkpoint_resume' => [
                'owner' => 'MD-B19:range-window-checkpoint-resume',
                'implementation' => [
                    'app/Application/MarketData/Services/ApiBackfillRangeAcquisitionService.php',
                ],
                'positive' => ['tests/Unit/MarketData/ApiBackfillRangeAcquisitionServiceTest.php', 'test_acquire_writes_window_ticker_checkpoints_for_resume'],
                'negative' => ['tests/Unit/MarketData/B19RangeWindowResumeStateTest.php', 'test_repeated_ticker_failures_are_not_escalated_to_systemic'],
            ],
            'range_window_warmup_calendar' => [
                'owner' => 'MD-B19:range-window-warmup-calendar',
                'implementation' => [
                    'app/Application/MarketData/Services/BackfillLifecycleOrchestrator.php',
                    'app/Infrastructure/Persistence/MarketData/MarketCalendarRepository.php',
                ],
                'positive' => ['tests/Unit/MarketData/B19RangeWindowWarmupCalendarTest.php', 'test_warmup_start_is_the_governed_trading_day_boundary_not_calendar_day_arithmetic'],
                'negative' => ['tests/Unit/MarketData/B19RangeWindowWarmupCalendarTest.php', 'test_a_non_trading_requested_date_fails_fast'],
            ],
            'release_gates' => [
                'owner' => 'MD-B19:release-gates',
                'implementation' => [
                    'docs/market_data/development/implementation/tests',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'reprocess_and_impact_amendments' => [
                'owner' => 'MD-B19:reprocess-and-impact-amendments',
                'implementation' => [
                    'app/Application/MarketData/Services/BackfillLifecycleOrchestrator.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'resumable_backfill' => [
                'owner' => 'MD-B19:resumable-backfill',
                'implementation' => [
                    'app/Application/MarketData/Services/BackfillLifecycleOrchestrator.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'retention_and_maintenance' => [
                'owner' => 'MD-B19:retention-and-maintenance',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataPipelineService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
            'scheduling_and_locking' => [
                'owner' => 'MD-B19:scheduling-and-locking',
                'implementation' => [
                    'app/Application/MarketData/Services/MarketDataPipelineService.php',
                ],
                'positive' => [],
                'negative' => [],
            ],
        ];
    }

    /** @param array<string,string> $row */
    public static function familyFor(array $row): string
    {
        $id = (string) $row['rule_id'];
        if (! isset(self::RULE_FAMILIES[$id])) {
            throw new RuntimeException('No reviewed MD-B19 proof family for '.$id
                .'. Add it to RULE_FAMILIES after reading the predicate; there is no default.');
        }

        return self::RULE_FAMILIES[$id];
    }

    /** @return array<int,array<string,string>> */
    public static function entries(string $root): array
    {
        return array_map(static function (array $row) {
            return ['rule_id' => $row['rule_id'], 'family' => self::familyFor($row)];
        }, MarketDataOperationsTraceabilitySpec::required($root));
    }
}
