<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * W06 — calendar provenance tier.
 *
 * Owner contract: docs/market_data/book/Market_Calendar_Requirements_Contract.md
 *                 — section "Calendar provenance tiers (LOCKED)"
 *
 * Exchanges publish holiday schedules a limited distance ahead. Rows beyond that horizon are
 * projections, and a projected weekday is an assumption about a date rather than a governed
 * trading session. Without a tier, the first trading year past the published horizon produces an
 * expected bar on every public holiday, and the resulting coverage failures read as provider
 * faults instead of calendar assumptions.
 *
 * The backfill derives the tier from evidence rather than from a date cutoff: a year carrying no
 * recorded national holiday cannot be a real IDX year, because IDX closes on fifteen or more
 * public holidays annually. Such a period is `PROJECTED`.
 */
class AddCalendarProvenanceTier extends Migration
{
    public function up()
    {
        if (Schema::hasTable('md_market_calendar_revisions') && ! Schema::hasColumn('md_market_calendar_revisions', 'provenance_tier')) {
            Schema::table('md_market_calendar_revisions', function (Blueprint $table) {
                $table->string('provenance_tier', 16)->nullable();
                $table->date('reconciled_at')->nullable();
                $table->string('reconciliation_source_ref', 255)->nullable();
            });
        }

        if (Schema::hasTable('market_calendar') && ! Schema::hasColumn('market_calendar', 'provenance_tier')) {
            Schema::table('market_calendar', function (Blueprint $table) {
                $table->string('provenance_tier', 16)->nullable();
                $table->date('reconciled_at')->nullable();
                $table->string('reconciliation_source_ref', 255)->nullable();
            });

            $this->backfillLegacyTiers();
        }
    }

    public function down()
    {
        foreach (['md_market_calendar_revisions', 'market_calendar'] as $tableName) {
            if (! Schema::hasTable($tableName)) {
                continue;
            }

            $existing = array_values(array_filter(
                ['provenance_tier', 'reconciled_at', 'reconciliation_source_ref'],
                function ($column) use ($tableName) {
                    return Schema::hasColumn($tableName, $column);
                }
            ));

            if ($existing !== []) {
                Schema::table($tableName, function (Blueprint $table) use ($existing) {
                    $table->dropColumn($existing);
                });
            }
        }
    }

    /**
     * A year with zero recorded national holidays was generated by weekday rule. Marking it
     * `VERIFIED` would assert a reconciliation nobody performed.
     */
    private function backfillLegacyTiers()
    {
        $years = DB::table('market_calendar')
            ->selectRaw('YEAR(cal_date) AS y, SUM(is_trading_day = 0 AND holiday_name IS NOT NULL AND holiday_name <> ?) AS holidays', ['AKHIR PEKAN'])
            ->groupBy(DB::raw('YEAR(cal_date)'))
            ->get();

        foreach ($years as $year) {
            DB::table('market_calendar')
                ->whereRaw('YEAR(cal_date) = ?', [(int) $year->y])
                ->update(['provenance_tier' => ((int) $year->holidays) > 0 ? 'VERIFIED' : 'PROJECTED']);
        }
    }
}
