<?php
/** GenerateWatchlistCurrentState.php — PHP 7.3+, no external deps. */
date_default_timezone_set('Asia/Jakarta');
function csvAssoc($p){$o=array();$f=fopen($p,'r');$h=fgetcsv($f);if(isset($h[0]))$h[0]=preg_replace('/^\xEF\xBB\xBF/','',$h[0]);while(($r=fgetcsv($f))!==false){$a=array();foreach($h as $i=>$k)$a[$k]=isset($r[$i])?trim($r[$i]):'';$o[]=$a;}fclose($f);return $o;}
$wr=realpath(dirname(__DIR__,3));$rr=realpath(dirname($wr,2));$epochFile=$wr.'/authority/governance/CURRENT_VERIFICATION_EPOCH.json';$verificationEpoch='UNKNOWN';if(is_file($epochFile)){$ep=json_decode(file_get_contents($epochFile),true);if(is_array($ep)&&!empty($ep['verification_epoch']))$verificationEpoch=$ep['verification_epoch'];}$matrix=csvAssoc($wr.'/authority/governance/STRATEGY_TO_IMPLEMENTATION_TRACEABILITY_MATRIX.csv');$deps=csvAssoc($wr.'/development/implementation/WS_DEPENDENCY_REGISTRY.csv');$records=csvAssoc($wr.'/records/WORK_RECORD_REGISTRY.csv');$relationships=csvAssoc($wr.'/records/WORK_RELATIONSHIP_REGISTRY.csv');
$required=0;$sat=0;$optional=0;$optionalSat=0;$notAssessed=0;$gaps=0;
foreach($matrix as $r){if($r['coverage_requirement']!=='REQUIRED'||$r['active']!=='YES')continue;if($r['applicability']==='OPTIONAL_CAPABILITY'){ $optional++; if($r['coverage_status']==='SATISFIED')$optionalSat++; continue;} $required++; if($r['coverage_status']==='SATISFIED')$sat++; elseif($r['coverage_status']==='NOT_ASSESSED')$notAssessed++; else $gaps++;}
$stageStates=array();$stageRows=array();$reg=$wr.'/development/implementation/WS_IMPLEMENTATION_STAGE_REGISTER.md';foreach(file($reg) as $line){if(preg_match('/^\|\s*`(WS-B\d{2})`\s*\|.*?\|\s*`([A-Z0-9_]+)`\s*\|/',$line,$m)){$stageRows[]=$m;$stageStates[$m[2]]=isset($stageStates[$m[2]])?$stageStates[$m[2]]+1:1;}}
$openDeps=0;foreach($deps as $d)if(in_array($d['status'],array('OPEN','WAITING_VERIFIED_DEPENDENCY'),true))$openDeps++;
$pct=$required?round($sat*100/$required,2):100;
$lines=array('# Watchlist Current State','','> **GENERATED — DO NOT EDIT MANUALLY**','> Sources: Stage Register, Strategy Traceability Matrix, Dependency Registry, Work Record Registry.','','Generated: '.date(DATE_ATOM),'','## Current Verification Epoch','','- Epoch: **`'.$verificationEpoch.'`**','- Pre-epoch PASS/FAIL/PARTIAL/DONE/READY: **historical-only**','- Existing implementation: **NOT_ASSESSED until current WS-Bxx evidence exists**','','## Strategy Coverage','','- Mandatory/conditional required rules: **'.$required.'**','- SATISFIED: **'.$sat.'**','- NOT_ASSESSED: **'.$notAssessed.'**','- Other open/gap states: **'.$gaps.'**','- Verified mandatory coverage: **'.$pct.'%**','- Optional rules (CONFIRM branch etc.): **'.$optional.'**','- Optional SATISFIED: **'.$optionalSat.'**','','## Stage Lifecycle','');foreach($stageStates as $s=>$c)$lines[]='- `'.$s.'`: **'.$c.'**';$lines[]='';$lines[]='## Current Registries';$lines[]='';$lines[]='- Work records registered: **'.count($records).'**';$lines[]='- Explicit work relationships registered: **'.count($relationships).'**';$lines[]='- Open/waiting dependencies: **'.$openDeps.'**';$lines[]='';$lines[]='## Production-use Review';$lines[]='';$lines[]='See `WS-B12` in `WS_IMPLEMENTATION_STAGE_REGISTER.md`. This generated summary does not infer production readiness.';$lines[]='';
$out=$wr.'/development/implementation/CURRENT_STATE.md';file_put_contents($out,implode(PHP_EOL,$lines).PHP_EOL);echo $out.PHP_EOL;
